-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\untitled_25_mayis\Kalman_28_yeni.vhd
-- Created: 2026-05-28 21:02:51
-- 
-- Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1e-08
-- Target subsystem base rate: 1e-08
-- Explicit user oversample request: 1000000x
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        1e-08
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- w_est                         ce_out        1e-08
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Kalman_28_yeni
-- Source Path: untitled_25_mayis/Kalman_28_yeni
-- Hierarchy Level: 0
-- Model version: 1.9
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.Kalman_28_yeni_pkg.ALL;

ENTITY Kalman_28_yeni IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        u                                 :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        data                              :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        ce_out                            :   OUT   std_logic;
        w_est                             :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En16
        );
END Kalman_28_yeni;


ARCHITECTURE rtl OF Kalman_28_yeni IS

  -- Component Declarations
  COMPONENT Kalman_28_yeni_tc
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          enb                             :   OUT   std_logic;
          enb_1_1_1                       :   OUT   std_logic;
          enb_1_1000000_0                 :   OUT   std_logic;
          enb_1_1000000_1                 :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT MATLAB_Function
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          enb_1_1000000_0                 :   IN    std_logic;
          enb_1_1000000_1                 :   IN    std_logic;
          u                               :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          data                            :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          w_est                           :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En16
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Kalman_28_yeni_tc
    USE ENTITY work.Kalman_28_yeni_tc(rtl);

  FOR ALL : MATLAB_Function
    USE ENTITY work.MATLAB_Function(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL enb_1_1000000_0                  : std_logic;
  SIGNAL enb_1_1000000_1                  : std_logic;
  SIGNAL enb_1_1_1                        : std_logic;
  SIGNAL stateControl_1                   : std_logic;
  SIGNAL stateControl_2                   : std_logic;
  SIGNAL enb_1_1000000_0_gated            : std_logic;
  SIGNAL u_1                              : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL MATLAB_Function_in_pipe1_reg     : vector_of_signed32(0 TO 4);  -- sfix32 [5]
  SIGNAL u_2                              : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL data_1                           : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL MATLAB_Function_in_pipe_reg      : vector_of_signed32(0 TO 4);  -- sfix32 [5]
  SIGNAL data_2                           : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL MATLAB_Function1_bypass_reg      : signed(31 DOWNTO 0);  -- sfix32
  SIGNAL u_3                              : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL MATLAB_Function_bypass_reg       : signed(31 DOWNTO 0);  -- sfix32
  SIGNAL data_3                           : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL enb_gated                        : std_logic;
  SIGNAL enb_1_1000000_1_gated            : std_logic;
  SIGNAL w_est_1                          : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL w_est_signed                     : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL w_est_2                          : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL w_est_last_value                 : signed(31 DOWNTO 0);  -- sfix32_En16

BEGIN
  u_Kalman_28_yeni_tc : Kalman_28_yeni_tc
    PORT MAP( clk => clk,
              reset => reset,
              clk_enable => clk_enable,
              enb => enb,
              enb_1_1_1 => enb_1_1_1,
              enb_1_1000000_0 => enb_1_1000000_0,
              enb_1_1000000_1 => enb_1_1000000_1
              );

  u_MATLAB_Function : MATLAB_Function
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb_gated,
              enb_1_1000000_0 => enb_1_1000000_0_gated,
              enb_1_1000000_1 => enb_1_1000000_1_gated,
              u => std_logic_vector(u_3),  -- sfix32_En16
              data => std_logic_vector(data_3),  -- sfix32_En16
              w_est => w_est_1  -- sfix32_En16
              );

  stateControl_1 <= '1';

  delayMatch_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        stateControl_2 <= '0';
      ELSIF enb_1_1000000_0 = '1' THEN
        stateControl_2 <= stateControl_1;
      END IF;
    END IF;
  END PROCESS delayMatch_process;


  enb_1_1000000_0_gated <= stateControl_2 AND enb_1_1000000_0;

  u_1 <= signed(u);

  MATLAB_Function_in_pipe1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        MATLAB_Function_in_pipe1_reg <= (OTHERS => to_signed(0, 32));
      ELSIF enb = '1' THEN
        MATLAB_Function_in_pipe1_reg(0) <= u_1;
        MATLAB_Function_in_pipe1_reg(1 TO 4) <= MATLAB_Function_in_pipe1_reg(0 TO 3);
      END IF;
    END IF;
  END PROCESS MATLAB_Function_in_pipe1_process;

  u_2 <= MATLAB_Function_in_pipe1_reg(4);

  data_1 <= signed(data);

  MATLAB_Function_in_pipe_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        MATLAB_Function_in_pipe_reg <= (OTHERS => to_signed(0, 32));
      ELSIF enb = '1' THEN
        MATLAB_Function_in_pipe_reg(0) <= data_1;
        MATLAB_Function_in_pipe_reg(1 TO 4) <= MATLAB_Function_in_pipe_reg(0 TO 3);
      END IF;
    END IF;
  END PROCESS MATLAB_Function_in_pipe_process;

  data_2 <= MATLAB_Function_in_pipe_reg(4);

  MATLAB_Function1_bypass_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        MATLAB_Function1_bypass_reg <= to_signed(0, 32);
      ELSIF enb_1_1000000_1 = '1' THEN
        MATLAB_Function1_bypass_reg <= u_2;
      END IF;
    END IF;
  END PROCESS MATLAB_Function1_bypass_process;

  
  u_3 <= u_2 WHEN enb_1_1000000_1 = '1' ELSE
      MATLAB_Function1_bypass_reg;

  MATLAB_Function_bypass_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        MATLAB_Function_bypass_reg <= to_signed(0, 32);
      ELSIF enb_1_1000000_1 = '1' THEN
        MATLAB_Function_bypass_reg <= data_2;
      END IF;
    END IF;
  END PROCESS MATLAB_Function_bypass_process;

  
  data_3 <= data_2 WHEN enb_1_1000000_1 = '1' ELSE
      MATLAB_Function_bypass_reg;

  enb_gated <= stateControl_2 AND enb;

  enb_1_1000000_1_gated <= stateControl_2 AND enb_1_1000000_1;

  w_est_signed <= signed(w_est_1);

  out0_bypass_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        w_est_last_value <= to_signed(0, 32);
      ELSIF enb_1_1000000_0_gated = '1' THEN
        w_est_last_value <= w_est_2;
      END IF;
    END IF;
  END PROCESS out0_bypass_process;


  
  w_est_2 <= w_est_last_value WHEN stateControl_2 = '0' ELSE
      w_est_signed;

  w_est <= std_logic_vector(w_est_2);

  ce_out <= enb_1_1_1;

END rtl;

