-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\untitled_25_mayis\MATLAB_Function.vhd
-- Created: 2026-05-28 21:02:51
-- 
-- Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MATLAB_Function
-- Source Path: untitled_25_mayis/Kalman_28_yeni/MATLAB Function
-- Hierarchy Level: 1
-- Model version: 1.9
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.Kalman_28_yeni_pkg.ALL;

ENTITY MATLAB_Function IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        enb_1_1000000_0                   :   IN    std_logic;
        enb_1_1000000_1                   :   IN    std_logic;
        u                                 :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        data                              :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        w_est                             :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En16
        );
END MATLAB_Function;


ARCHITECTURE rtl OF MATLAB_Function IS

  -- Constants
  CONSTANT nc                             : matrix_of_signed32(0 TO 1, 0 TO 1) := 
    (( to_signed(55705, 32), to_signed(13107, 32) ), ( to_signed(-655, 32), to_signed(26214, 32) ));  -- sfix32 [2x2]
  CONSTANT nc_2                           : vector_of_signed32(0 TO 1) := 
    (to_signed(85524, 32), to_signed(6553, 32));  -- sfix32 [2]
  CONSTANT nc_4                           : vector_of_signed32(0 TO 1) := 
    (to_signed(65536, 32), to_signed(0, 32));  -- sfix32 [2]
  CONSTANT nc_6                           : matrix_of_signed32(0 TO 1, 0 TO 1) := 
    (( to_signed(65536, 32), to_signed(0, 32) ), ( to_signed(0, 32), to_signed(65536, 32) ));  -- sfix32 [2x2]
  CONSTANT nc_8                           : matrix_of_signed32(0 TO 1, 0 TO 1) := 
    (( to_signed(55705, 32), to_signed(-655, 32) ), ( to_signed(13107, 32), to_signed(26214, 32) ));  -- sfix32 [2x2]
  CONSTANT nc_10                          : matrix_of_signed32(0 TO 1, 0 TO 1) := 
    (( to_signed(13107, 32), to_signed(0, 32) ), ( to_signed(0, 32), to_signed(13107, 32) ));  -- sfix32 [2x2]
  CONSTANT nc_12                          : vector_of_signed32(0 TO 1) := 
    (to_signed(65536, 32), to_signed(0, 32));  -- sfix32 [2]
  CONSTANT C_divbyzero_p                  : signed(64 DOWNTO 0) := 
    signed'("01111111111111111111111111111111111111111111111111111111111111111");  -- sfix65
  CONSTANT C_divbyzero_n                  : signed(64 DOWNTO 0) := 
    signed'("10000000000000000000000000000000000000000000000000000000000000000");  -- sfix65

  -- Signals
  SIGNAL c                                : vector_of_signed65(0 TO 1);  -- sfix65_En32 [2]
  SIGNAL Ad                               : matrix_of_signed32(0 TO 1, 0 TO 1);  -- sfix32_En16 [2x2]
  SIGNAL Bd                               : vector_of_signed32(0 TO 1);  -- sfix32_En16 [2]
  SIGNAL u_1                              : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL u_2                              : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL tmp                              : vector_of_signed64(0 TO 1);  -- sfix64_En32 [2]
  SIGNAL tmp_1                            : vector_of_signed64(0 TO 1);  -- sfix64_En32 [2]
  SIGNAL tmp_2                            : vector_of_signed66(0 TO 1);  -- sfix66_En32 [2]
  SIGNAL tmp_3                            : vector_of_signed66(0 TO 1);  -- sfix66_En32 [2]
  SIGNAL c_2                              : signed(97 DOWNTO 0);  -- sfix98_En48
  SIGNAL c_3                              : vector_of_signed65(0 TO 1);  -- sfix65_En32 [2]
  SIGNAL Cd                               : vector_of_signed32(0 TO 1);  -- sfix32_En16 [2]
  SIGNAL c_4                              : matrix_of_signed98(0 TO 1, 0 TO 1);  -- sfix98_En48 [2x2]
  SIGNAL c_5                              : matrix_of_signed65(0 TO 1, 0 TO 1);  -- sfix65_En32 [2x2]
  SIGNAL P_reg_ctrl_const_out             : std_logic;
  SIGNAL P_reg_ctrl_const_out_1           : std_logic;
  SIGNAL c56_P_reg_Initial_Val_out        : vector_of_signed32(0 TO 3);  -- sfix32_En16 [4]
  SIGNAL P_reg_Initial_Val_out            : matrix_of_signed32(0 TO 1, 0 TO 1);  -- sfix32_En16 [2x2]
  SIGNAL c976_P_reg_Initial_Val_out       : vector_of_signed32(0 TO 3);  -- sfix32_En16 [4]
  SIGNAL P_reg_ctrl_delay_out             : std_logic;
  SIGNAL P_reg_switch_bypass_reg          : vector_of_signed32(0 TO 3);  -- sfix32 [4]
  SIGNAL c929_P_reg_Initial_Val_out       : vector_of_signed32(0 TO 3);  -- sfix32_En16 [4]
  SIGNAL P_reg_Initial_Val_out_1          : matrix_of_signed32(0 TO 1, 0 TO 1);  -- sfix32_En16 [2x2]
  SIGNAL c318_P_reg_Initial_Val_out       : vector_of_signed32(0 TO 3);  -- sfix32_En16 [4]
  SIGNAL c_6                              : matrix_of_signed65(0 TO 1, 0 TO 1);  -- sfix65_En32 [2x2]
  SIGNAL I                                : matrix_of_signed32(0 TO 1, 0 TO 1);  -- sfix32_En16 [2x2]
  SIGNAL c40_I                            : vector_of_signed32(0 TO 3);  -- sfix32_En16 [4]
  SIGNAL c40_tmp                          : vector_of_signed33(0 TO 3);  -- sfix33_En16 [4]
  SIGNAL tmp_4                            : matrix_of_signed33(0 TO 1, 0 TO 1);  -- sfix33_En16 [2x2]
  SIGNAL c79_tmp                          : vector_of_signed33(0 TO 3);  -- sfix33_En16 [4]
  SIGNAL c_8                              : matrix_of_signed64(0 TO 1, 0 TO 1);  -- sfix64_En32 [2x2]
  SIGNAL tmp_5                            : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL sel                              : std_logic;
  SIGNAL s                                : std_logic;
  SIGNAL tmp_6                            : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_7                            : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_8                            : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_9                            : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL sel_1                            : std_logic;
  SIGNAL s_1                              : std_logic;
  SIGNAL tmp_10                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_11                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_12                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL Ad_t                             : matrix_of_signed32(0 TO 1, 0 TO 1);  -- sfix32_En16 [2x2]
  SIGNAL Q                                : matrix_of_signed32(0 TO 1, 0 TO 1);  -- sfix32_En16 [2x2]
  SIGNAL c3_Q                             : vector_of_signed32(0 TO 3);  -- sfix32_En16 [4]
  SIGNAL c3_tmp                           : vector_of_signed99(0 TO 3);  -- sfix99_En48 [4]
  SIGNAL Cd_t                             : vector_of_signed32(0 TO 1);  -- sfix32_En16 [2]
  SIGNAL R0                               : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL tmp_13                           : signed(32 DOWNTO 0);  -- sfix33_En16
  SIGNAL alpha                            : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL data_1                           : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL data_2                           : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL tmp_14                           : signed(32 DOWNTO 0);  -- sfix33_En16
  SIGNAL rd_8_reg                         : vector_of_signed33(0 TO 5);  -- sfix33 [6]
  SIGNAL tmp_15                           : signed(32 DOWNTO 0);  -- sfix33_En16
  SIGNAL c_12                             : signed(64 DOWNTO 0);  -- sfix65_En32
  SIGNAL R_k                              : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL R_k_1                            : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL c_13                             : vector_of_signed65(0 TO 1);  -- sfix65_En16 [2]
  SIGNAL rd_37_reg                        : vector_of_signed65(0 TO 39);  -- sfix65 [40]
  SIGNAL c_14                             : vector_of_signed65(0 TO 1);  -- sfix65_En16 [2]
  SIGNAL c_15                             : vector_of_signed65(0 TO 1);  -- sfix65_En32 [2]
  SIGNAL K                                : vector_of_signed32(0 TO 1);  -- sfix32_En16 [2]
  SIGNAL residual                         : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL rd_64_reg                        : vector_of_signed32(0 TO 13);  -- sfix32 [14]
  SIGNAL residual_1                       : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL P_pred                           : matrix_of_signed32(0 TO 1, 0 TO 1);  -- sfix32_En16 [2x2]
  SIGNAL c_17                             : vector_of_signed65(0 TO 1);  -- sfix65_En32 [2]
  SIGNAL rd_38_reg                        : vector_of_signed65(0 TO 33);  -- sfix65 [34]
  SIGNAL c_18                             : vector_of_signed65(0 TO 1);  -- sfix65_En32 [2]
  SIGNAL S_k                              : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL c_19                             : vector_of_signed65(0 TO 1);  -- sfix65_En16 [2]
  SIGNAL c_20                             : vector_of_signed65(0 TO 1);  -- sfix65_En16 [2]
  SIGNAL K_1                              : vector_of_signed32(0 TO 1);  -- sfix32_En16 [2]
  SIGNAL rd_40_reg                        : vector_of_signed32(0 TO 3);  -- sfix32 [4]
  SIGNAL K_2                              : vector_of_signed32(0 TO 1);  -- sfix32_En16 [2]
  SIGNAL S_k_1                            : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL alpha_cast                       : signed(32 DOWNTO 0);  -- sfix33_En16
  SIGNAL alpha_cast_1                     : signed(32 DOWNTO 0);  -- sfix33_En16
  SIGNAL y                                : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL y_1                              : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL S_k_2                            : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL R_k_2                            : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL R_k_3                            : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL R_k_4                            : std_logic;
  SIGNAL R_k_5                            : std_logic;
  SIGNAL R_k_6                            : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL R_k_7                            : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL residual_2                       : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL alpha_cast_2                     : signed(32 DOWNTO 0);  -- sfix33_En16
  SIGNAL alpha_cast_3                     : signed(32 DOWNTO 0);  -- sfix33_En16
  SIGNAL y_2                              : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL y_3                              : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL residual_3                       : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL x_pred                           : vector_of_signed32(0 TO 1);  -- sfix32_En16 [2]
  SIGNAL c_25                             : signed(64 DOWNTO 0);  -- sfix65_En32
  SIGNAL c_26                             : signed(64 DOWNTO 0);  -- sfix65_En32
  SIGNAL y_pred                           : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL y_pred_1                         : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL tmp_16                           : signed(32 DOWNTO 0);  -- sfix33_En16
  SIGNAL tmp_17                           : signed(32 DOWNTO 0);  -- sfix33_En16
  SIGNAL adder_sub_cast                   : signed(33 DOWNTO 0);  -- sfix34_En16
  SIGNAL adder_sub_cast_1                 : signed(33 DOWNTO 0);  -- sfix34_En16
  SIGNAL adder_sub_temp                   : signed(33 DOWNTO 0);  -- sfix34_En16
  SIGNAL tmp_18                           : signed(32 DOWNTO 0);  -- sfix33_En16
  SIGNAL tmp_19                           : signed(32 DOWNTO 0);  -- sfix33_En16
  SIGNAL residual_4                       : std_logic;
  SIGNAL rd_15_reg                        : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL residual_5                       : std_logic;
  SIGNAL y_4                              : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL y_5                              : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL tmp_20                           : signed(63 DOWNTO 0);  -- sfix64_En32
  SIGNAL tmp_21                           : signed(63 DOWNTO 0);  -- sfix64_En32
  SIGNAL tmp_22                           : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL tmp_23                           : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL tmp_24                           : signed(32 DOWNTO 0);  -- sfix33_En16
  SIGNAL tmp_25                           : signed(32 DOWNTO 0);  -- sfix33_En16
  SIGNAL adder_add_cast                   : signed(33 DOWNTO 0);  -- sfix34_En16
  SIGNAL adder_add_cast_1                 : signed(33 DOWNTO 0);  -- sfix34_En16
  SIGNAL adder_add_temp                   : signed(33 DOWNTO 0);  -- sfix34_En16
  SIGNAL tmp_26                           : signed(32 DOWNTO 0);  -- sfix33_En16
  SIGNAL tmp_27                           : signed(32 DOWNTO 0);  -- sfix33_En16
  SIGNAL R_k_8                            : std_logic;
  SIGNAL rd_26_reg                        : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL R_k_9                            : std_logic;
  SIGNAL R_k_10                           : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL R_k_11                           : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL tmp_28                           : signed(32 DOWNTO 0);  -- sfix33_En16
  SIGNAL tmp_29                           : signed(32 DOWNTO 0);  -- sfix33_En16
  SIGNAL P                                : matrix_of_signed32(0 TO 1, 0 TO 1);  -- sfix32_En16 [2x2]
  SIGNAL P_1                              : std_logic;
  SIGNAL P_2                              : std_logic;
  SIGNAL sel_2                            : std_logic;
  SIGNAL sel_2_1                          : std_logic;
  SIGNAL tmp_30                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_31                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL P_3                              : matrix_of_signed32(0 TO 1, 0 TO 1);  -- sfix32_En16 [2x2]
  SIGNAL P_4                              : std_logic;
  SIGNAL P_5                              : std_logic;
  SIGNAL sel_2_2                          : std_logic;
  SIGNAL sel_2_3                          : std_logic;
  SIGNAL tmp_32                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_33                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL P_6                              : matrix_of_signed32(0 TO 1, 0 TO 1);  -- sfix32_En16 [2x2]
  SIGNAL tmp_34                           : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL tmp_35                           : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL tmp_36                           : signed(32 DOWNTO 0);  -- sfix33_En16
  SIGNAL tmp_37                           : signed(32 DOWNTO 0);  -- sfix33_En16
  SIGNAL tmp_38                           : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL tmp_39                           : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL tmp_40                           : signed(32 DOWNTO 0);  -- sfix33_En16
  SIGNAL tmp_41                           : signed(32 DOWNTO 0);  -- sfix33_En16
  SIGNAL adder_add_cast_2                 : signed(33 DOWNTO 0);  -- sfix34_En16
  SIGNAL adder_add_cast_3                 : signed(33 DOWNTO 0);  -- sfix34_En16
  SIGNAL adder_add_temp_1                 : signed(33 DOWNTO 0);  -- sfix34_En16
  SIGNAL tmp_42                           : signed(32 DOWNTO 0);  -- sfix33_En16
  SIGNAL tmp_43                           : signed(32 DOWNTO 0);  -- sfix33_En16
  SIGNAL p92tmp_div_temp                  : signed(62 DOWNTO 0);  -- sfix63_En16
  SIGNAL p92tmp_cast                      : signed(62 DOWNTO 0);  -- sfix63_En46
  SIGNAL tmp_44                           : signed(32 DOWNTO 0);  -- sfix33_En16
  SIGNAL P12                              : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL c1134_P_pred                     : vector_of_signed32(0 TO 3);  -- sfix32_En16 [4]
  SIGNAL rd_45_reg                        : vector_of_signed32(0 TO 95);  -- sfix32 [96]
  SIGNAL c1134_P_pred_1                   : vector_of_signed32(0 TO 3);  -- sfix32_En16 [4]
  SIGNAL P_pred_1                         : matrix_of_signed32(0 TO 1, 0 TO 1);  -- sfix32_En16 [2x2]
  SIGNAL K_3                              : vector_of_signed32(0 TO 1);  -- sfix32_En16 [2]
  SIGNAL c_38                             : matrix_of_signed64(0 TO 1, 0 TO 1);  -- sfix64_En32 [2x2]
  SIGNAL c76_c                            : vector_of_signed64(0 TO 3);  -- sfix64_En32 [4]
  SIGNAL c76_c_1                          : vector_of_signed64(0 TO 3);  -- sfix64_En32 [4]
  SIGNAL c77_tmp                          : vector_of_signed32(0 TO 3);  -- sfix32_En16 [4]
  SIGNAL c77_tmp_1                        : vector_of_signed32(0 TO 3);  -- sfix32_En16 [4]
  SIGNAL c78_tmp                          : vector_of_signed33(0 TO 3);  -- sfix33_En16 [4]
  SIGNAL c78_tmp_1                        : vector_of_signed33(0 TO 3);  -- sfix33_En16 [4]
  SIGNAL adder_sub_cast_2                 : vector_of_signed34(0 TO 3);  -- sfix34_En16 [4]
  SIGNAL adder_sub_cast_3                 : vector_of_signed34(0 TO 3);  -- sfix34_En16 [4]
  SIGNAL adder_sub_temp_1                 : vector_of_signed34(0 TO 3);  -- sfix34_En16 [4]
  SIGNAL c79_tmp_1                        : vector_of_signed33(0 TO 3);  -- sfix33_En16 [4]
  SIGNAL c79_tmp_2                        : vector_of_signed33(0 TO 3);  -- sfix33_En16 [4]
  SIGNAL c81_a0                           : vector_of_signed32(0 TO 3);  -- sfix32_En16 [4]
  SIGNAL a0                               : matrix_of_signed32(0 TO 1, 0 TO 1);  -- sfix32_En16 [2x2]
  SIGNAL c_43                             : matrix_of_signed65(0 TO 1, 0 TO 1);  -- sfix65_En32 [2x2]
  SIGNAL c85_c                            : vector_of_signed65(0 TO 3);  -- sfix65_En32 [4]
  SIGNAL c85_c_1                          : vector_of_signed65(0 TO 3);  -- sfix65_En32 [4]
  SIGNAL c65_P                            : vector_of_signed32(0 TO 3);  -- sfix32_En16 [4]
  SIGNAL c1118_P                          : vector_of_signed32(0 TO 3);  -- sfix32_En16 [4]
  SIGNAL rd_47_reg                        : vector_of_signed32(0 TO 11);  -- sfix32 [12]
  SIGNAL c1118_P_1                        : vector_of_signed32(0 TO 3);  -- sfix32_En16 [4]
  SIGNAL P_7                              : matrix_of_signed32(0 TO 1, 0 TO 1);  -- sfix32_En16 [2x2]
  SIGNAL c1120_P                          : vector_of_signed32(0 TO 3);  -- sfix32_En16 [4]
  SIGNAL rd_53_reg                        : vector_of_signed32(0 TO 11);  -- sfix32 [12]
  SIGNAL c1120_P_1                        : vector_of_signed32(0 TO 3);  -- sfix32_En16 [4]
  SIGNAL P_8                              : matrix_of_signed32(0 TO 1, 0 TO 1);  -- sfix32_En16 [2x2]
  SIGNAL c1116_P                          : vector_of_signed32(0 TO 3);  -- sfix32_En16 [4]
  SIGNAL rd_57_reg                        : vector_of_signed32(0 TO 11);  -- sfix32 [12]
  SIGNAL c1116_P_1                        : vector_of_signed32(0 TO 3);  -- sfix32_En16 [4]
  SIGNAL P_9                              : matrix_of_signed32(0 TO 1, 0 TO 1);  -- sfix32_En16 [2x2]
  SIGNAL P_10                             : matrix_of_signed32(0 TO 1, 0 TO 1);  -- sfix32_En16 [2x2]
  SIGNAL c1143_P                          : vector_of_signed32(0 TO 3);  -- sfix32_En16 [4]
  SIGNAL c1143_P_1                        : vector_of_signed32(0 TO 3);  -- sfix32_En16 [4]
  SIGNAL P_11                             : matrix_of_signed32(0 TO 1, 0 TO 1);  -- sfix32_En16 [2x2]
  SIGNAL c1143_P_2                        : vector_of_signed32(0 TO 3);  -- sfix32_En16 [4]
  SIGNAL P_reg_bypass_reg                 : vector_of_signed32(0 TO 3);  -- sfix32 [4]
  SIGNAL P_12                             : vector_of_signed32(0 TO 3);  -- sfix32_En16 [4]
  SIGNAL P_reg_out                        : matrix_of_signed32(0 TO 1, 0 TO 1);  -- sfix32_En16 [2x2]
  SIGNAL c318_P_reg_out                   : vector_of_signed32(0 TO 3);  -- sfix32_En16 [4]
  SIGNAL c318_P                           : vector_of_signed32(0 TO 3);  -- sfix32_En16 [4]
  SIGNAL P_13                             : matrix_of_signed32(0 TO 1, 0 TO 1);  -- sfix32_En16 [2x2]
  SIGNAL c886_P                           : vector_of_signed32(0 TO 3);  -- sfix32_En16 [4]
  SIGNAL c934_P                           : vector_of_signed32(0 TO 3);  -- sfix32_En16 [4]
  SIGNAL P_14                             : matrix_of_signed32(0 TO 1, 0 TO 1);  -- sfix32_En16 [2x2]
  SIGNAL c1136_P                          : vector_of_signed32(0 TO 3);  -- sfix32_En16 [4]
  SIGNAL c1136_P_1                        : vector_of_signed32(0 TO 3);  -- sfix32_En16 [4]
  SIGNAL P_15                             : matrix_of_signed32(0 TO 1, 0 TO 1);  -- sfix32_En16 [2x2]
  SIGNAL c_46                             : matrix_of_signed65(0 TO 1, 0 TO 1);  -- sfix65_En32 [2x2]
  SIGNAL c92_c                            : vector_of_signed65(0 TO 3);  -- sfix65_En32 [4]
  SIGNAL c_47                             : matrix_of_signed65(0 TO 1, 0 TO 1);  -- sfix65_En32 [2x2]
  SIGNAL c_49                             : matrix_of_signed98(0 TO 1, 0 TO 1);  -- sfix98_En48 [2x2]
  SIGNAL c94_c                            : vector_of_signed98(0 TO 3);  -- sfix98_En48 [4]
  SIGNAL c95_tmp                          : vector_of_signed99(0 TO 3);  -- sfix99_En48 [4]
  SIGNAL c95_tmp_1                        : vector_of_signed99(0 TO 3);  -- sfix99_En48 [4]
  SIGNAL adder_add_cast_4                 : vector_of_signed100(0 TO 3);  -- sfix100_En48 [4]
  SIGNAL adder_add_cast_5                 : vector_of_signed100(0 TO 3);  -- sfix100_En48 [4]
  SIGNAL adder_add_temp_2                 : vector_of_signed100(0 TO 3);  -- sfix100_En48 [4]
  SIGNAL c96_tmp                          : vector_of_signed99(0 TO 3);  -- sfix99_En48 [4]
  SIGNAL c96_tmp_1                        : vector_of_signed99(0 TO 3);  -- sfix99_En48 [4]
  SIGNAL c84_P_pred                       : vector_of_signed32(0 TO 3);  -- sfix32_En16 [4]
  SIGNAL c_53                             : vector_of_signed65(0 TO 1);  -- sfix65_En32 [2]
  SIGNAL c_55                             : signed(97 DOWNTO 0);  -- sfix98_En48
  SIGNAL c_56                             : signed(97 DOWNTO 0);  -- sfix98_En48
  SIGNAL tmp_45                           : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL tmp_46                           : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL tmp_47                           : signed(32 DOWNTO 0);  -- sfix33_En16
  SIGNAL rd_25_reg                        : vector_of_signed33(0 TO 13);  -- sfix33 [14]
  SIGNAL tmp_48                           : signed(32 DOWNTO 0);  -- sfix33_En16
  SIGNAL adder_add_cast_6                 : signed(33 DOWNTO 0);  -- sfix34_En16
  SIGNAL adder_add_cast_7                 : signed(33 DOWNTO 0);  -- sfix34_En16
  SIGNAL adder_add_temp_3                 : signed(33 DOWNTO 0);  -- sfix34_En16
  SIGNAL tmp_49                           : signed(32 DOWNTO 0);  -- sfix33_En16
  SIGNAL tmp_50                           : signed(32 DOWNTO 0);  -- sfix33_En16
  SIGNAL S_k_3                            : std_logic;
  SIGNAL rd_34_reg                        : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL S_k_4                            : std_logic;
  SIGNAL y_6                              : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL y_7                              : std_logic;
  SIGNAL y_8                              : std_logic;
  SIGNAL K_9                              : vector_of_signed32(0 TO 1);  -- sfix32_En16 [2]
  SIGNAL tmp_51                           : vector_of_signed64(0 TO 1);  -- sfix64_En32 [2]
  SIGNAL tmp_52                           : vector_of_signed64(0 TO 1);  -- sfix64_En32 [2]
  SIGNAL tmp_53                           : vector_of_signed32(0 TO 1);  -- sfix32_En16 [2]
  SIGNAL tmp_54                           : vector_of_signed32(0 TO 1);  -- sfix32_En16 [2]
  SIGNAL tmp_55                           : vector_of_signed33(0 TO 1);  -- sfix33_En16 [2]
  SIGNAL tmp_56                           : vector_of_signed33(0 TO 1);  -- sfix33_En16 [2]
  SIGNAL tmp_57                           : vector_of_signed32(0 TO 1);  -- sfix32_En16 [2]
  SIGNAL x_est                            : vector_of_signed32(0 TO 1);  -- sfix32_En16 [2]
  SIGNAL x_est_reg_bypass_reg             : vector_of_signed32(0 TO 1);  -- sfix32 [2]
  SIGNAL x_est_1                          : vector_of_signed32(0 TO 1);  -- sfix32_En16 [2]
  SIGNAL x_est_2                          : vector_of_signed32(0 TO 1);  -- sfix32_En16 [2]
  SIGNAL x_est_3                          : vector_of_signed32(0 TO 1);  -- sfix32_En16 [2]
  SIGNAL c_63                             : vector_of_signed65(0 TO 1);  -- sfix65_En32 [2]
  SIGNAL tmp_58                           : vector_of_signed66(0 TO 1);  -- sfix66_En32 [2]
  SIGNAL rd_4_reg                         : vector_of_signed66(0 TO 3);  -- sfix66 [4]
  SIGNAL tmp_59                           : vector_of_signed66(0 TO 1);  -- sfix66_En32 [2]
  SIGNAL adder_add_cast_8                 : vector_of_signed67(0 TO 1);  -- sfix67_En32 [2]
  SIGNAL adder_add_cast_9                 : vector_of_signed67(0 TO 1);  -- sfix67_En32 [2]
  SIGNAL adder_add_temp_4                 : vector_of_signed67(0 TO 1);  -- sfix67_En32 [2]
  SIGNAL tmp_60                           : vector_of_signed66(0 TO 1);  -- sfix66_En32 [2]
  SIGNAL tmp_61                           : vector_of_signed66(0 TO 1);  -- sfix66_En32 [2]
  SIGNAL x_pred_1                         : vector_of_signed32(0 TO 1);  -- sfix32_En16 [2]
  SIGNAL tmp_62                           : vector_of_signed33(0 TO 1);  -- sfix33_En16 [2]
  SIGNAL rd_62_reg                        : vector_of_signed33(0 TO 43);  -- sfix33 [44]
  SIGNAL tmp_63                           : vector_of_signed33(0 TO 1);  -- sfix33_En16 [2]
  SIGNAL adder_add_cast_10                : vector_of_signed34(0 TO 1);  -- sfix34_En16 [2]
  SIGNAL adder_add_cast_11                : vector_of_signed34(0 TO 1);  -- sfix34_En16 [2]
  SIGNAL adder_add_temp_5                 : vector_of_signed34(0 TO 1);  -- sfix34_En16 [2]
  SIGNAL tmp_64                           : vector_of_signed33(0 TO 1);  -- sfix33_En16 [2]
  SIGNAL tmp_65                           : vector_of_signed33(0 TO 1);  -- sfix33_En16 [2]
  SIGNAL tmp_66                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL w_est_1                          : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL alpha_bypass_reg                 : signed(31 DOWNTO 0);  -- sfix32
  SIGNAL w_est_tmp                        : signed(31 DOWNTO 0);  -- sfix32_En16

BEGIN
  c <= (OTHERS => to_signed(0, 65));

  Ad <= nc;

  Bd <= nc_2;

  u_1 <= signed(u);

  rd_0_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        u_2 <= to_signed(0, 32);
      ELSIF enb = '1' THEN
        u_2 <= u_1;
      END IF;
    END IF;
  END PROCESS rd_0_process;



  tmp_gen: FOR t_0 IN 0 TO 1 GENERATE
    tmp(t_0) <= Bd(t_0) * u_2;
  END GENERATE tmp_gen;


  rd_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        tmp_1 <= (OTHERS => to_signed(0, 64));
      ELSIF enb = '1' THEN
        tmp_1 <= tmp;
      END IF;
    END IF;
  END PROCESS rd_1_process;



  tmp_2_gen: FOR ii IN 0 TO 1 GENERATE
    tmp_2(ii) <= resize(tmp_1(ii), 66);
  END GENERATE tmp_2_gen;


  rd_5_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        tmp_3 <= (OTHERS => to_signed(0, 66));
      ELSIF enb = '1' THEN
        tmp_3 <= tmp_2;
      END IF;
    END IF;
  END PROCESS rd_5_process;


  c_2 <= to_signed(0, 98);

  c_3 <= (OTHERS => to_signed(0, 65));

  Cd <= nc_4;

  c_4 <= (OTHERS => (OTHERS => to_signed(0, 98)));

  c_5 <= (OTHERS => (OTHERS => to_signed(0, 65)));

  P_reg_ctrl_const_out <= '1';

  P_reg_ctrl_delay_output_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        P_reg_ctrl_const_out_1 <= '0';
      ELSIF enb_1_1000000_1 = '1' THEN
        P_reg_ctrl_const_out_1 <= P_reg_ctrl_const_out;
      END IF;
    END IF;
  END PROCESS P_reg_ctrl_delay_output_process;


  c56_P_reg_Initial_Val_out(0) <= to_signed(327680, 32);
  c56_P_reg_Initial_Val_out(1) <= to_signed(0, 32);
  c56_P_reg_Initial_Val_out(2) <= to_signed(0, 32);
  c56_P_reg_Initial_Val_out(3) <= to_signed(1310720, 32);

  P_reg_Initial_Val_out_gen1: FOR d1 IN 0 TO 1 GENERATE
    P_reg_Initial_Val_out_gen: FOR d0 IN 0 TO 1 GENERATE
      P_reg_Initial_Val_out(d0, d1) <= c56_P_reg_Initial_Val_out(d0 + (d1 * 2));
    END GENERATE;
  END GENERATE;

  c976_P_reg_Initial_Val_out_gen1: FOR d1 IN 0 TO 1 GENERATE
    c976_P_reg_Initial_Val_out_gen: FOR d0 IN 0 TO 1 GENERATE
      c976_P_reg_Initial_Val_out(d0 + (d1 * 2)) <= P_reg_Initial_Val_out(d0, d1);
    END GENERATE;
  END GENERATE;

  P_reg_ctrl_delay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        P_reg_ctrl_delay_out <= '0';
      ELSIF enb_1_1000000_0 = '1' THEN
        P_reg_ctrl_delay_out <= P_reg_ctrl_const_out_1;
      END IF;
    END IF;
  END PROCESS P_reg_ctrl_delay_process;


  P_reg_switch_bypass_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        P_reg_switch_bypass_reg <= (OTHERS => to_signed(0, 32));
      ELSIF enb_1_1000000_1 = '1' THEN
        P_reg_switch_bypass_reg <= c976_P_reg_Initial_Val_out;
      END IF;
    END IF;
  END PROCESS P_reg_switch_bypass_process;

  
  c929_P_reg_Initial_Val_out <= c976_P_reg_Initial_Val_out WHEN enb_1_1000000_1 = '1' ELSE
      P_reg_switch_bypass_reg;

  P_reg_Initial_Val_out_1_gen1: FOR d1 IN 0 TO 1 GENERATE
    P_reg_Initial_Val_out_1_gen: FOR d0 IN 0 TO 1 GENERATE
      P_reg_Initial_Val_out_1(d0, d1) <= c929_P_reg_Initial_Val_out(d0 + (d1 * 2));
    END GENERATE;
  END GENERATE;

  c318_P_reg_Initial_Val_out_gen1: FOR d1 IN 0 TO 1 GENERATE
    c318_P_reg_Initial_Val_out_gen: FOR d0 IN 0 TO 1 GENERATE
      c318_P_reg_Initial_Val_out(d0 + (d1 * 2)) <= P_reg_Initial_Val_out_1(d0, d1);
    END GENERATE;
  END GENERATE;

  c_6 <= (OTHERS => (OTHERS => to_signed(0, 65)));

  I <= nc_6;

  c40_I_gen1: FOR d1 IN 0 TO 1 GENERATE
    c40_I_gen: FOR d0 IN 0 TO 1 GENERATE
      c40_I(d0 + (d1 * 2)) <= I(d0, d1);
    END GENERATE;
  END GENERATE;


  c40_tmp_gen: FOR ii1 IN 0 TO 3 GENERATE
    c40_tmp(ii1) <= resize(c40_I(ii1), 33);
  END GENERATE c40_tmp_gen;


  tmp_4_gen1: FOR d1 IN 0 TO 1 GENERATE
    tmp_4_gen: FOR d0 IN 0 TO 1 GENERATE
      tmp_4(d0, d1) <= c40_tmp(d0 + (d1 * 2));
    END GENERATE;
  END GENERATE;

  c79_tmp_gen1: FOR d1 IN 0 TO 1 GENERATE
    c79_tmp_gen: FOR d0 IN 0 TO 1 GENERATE
      c79_tmp(d0 + (d1 * 2)) <= tmp_4(d0, d1);
    END GENERATE;
  END GENERATE;

  c_8 <= (OTHERS => (OTHERS => to_signed(0, 64)));

  tmp_5 <= to_signed(6, 32);

  sel <= '0';

  s <= '1';

  tmp_6 <= to_signed(-1, 32);

  tmp_7 <= to_signed(16#00000000#, 32);

  tmp_8 <= to_signed(16#00000000#, 32);

  tmp_9 <= to_signed(6, 32);

  sel_1 <= '0';

  s_1 <= '1';

  tmp_10 <= to_signed(-1, 32);

  tmp_11 <= to_signed(16#00000001#, 32);

  tmp_12 <= to_signed(16#00000001#, 32);

  Ad_t <= nc_8;

  Q <= nc_10;

  c3_Q_gen1: FOR d1 IN 0 TO 1 GENERATE
    c3_Q_gen: FOR d0 IN 0 TO 1 GENERATE
      c3_Q(d0 + (d1 * 2)) <= Q(d0, d1);
    END GENERATE;
  END GENERATE;


  c3_tmp_gen: FOR ii2 IN 0 TO 3 GENERATE
    c3_tmp(ii2) <= resize(c3_Q(ii2) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 99);
  END GENERATE c3_tmp_gen;


  Cd_t <= nc_12;

  R0 <= to_signed(327680, 32);

  tmp_13 <= resize(R0, 33);

  alpha <= to_signed(1310, 32);

  data_1 <= signed(data);

  rd_7_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        data_2 <= to_signed(0, 32);
      ELSIF enb = '1' THEN
        data_2 <= data_1;
      END IF;
    END IF;
  END PROCESS rd_7_process;


  tmp_14 <= resize(data_2, 33);

  rd_8_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rd_8_reg <= (OTHERS => to_signed(0, 33));
      ELSIF enb = '1' THEN
        rd_8_reg(0) <= tmp_14;
        rd_8_reg(1 TO 5) <= rd_8_reg(0 TO 4);
      END IF;
    END IF;
  END PROCESS rd_8_process;

  tmp_15 <= rd_8_reg(5);

  c_12 <= to_signed(0, 65);

  R_k <= to_signed(1310720, 32);

  R_k_1 <= to_signed(6553, 32);

  rd_37_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rd_37_reg <= (OTHERS => to_signed(0, 65));
      ELSIF enb = '1' THEN
        rd_37_reg(0 TO 1) <= c_13(0 TO 1);
        rd_37_reg(2 TO 39) <= rd_37_reg(0 TO 37);
      END IF;
    END IF;
  END PROCESS rd_37_process;

  c_14(0 TO 1) <= rd_37_reg(38 TO 39);

  c_15 <= (OTHERS => to_signed(0, 65));

  K <= (OTHERS => to_signed(0, 32));

  rd_64_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rd_64_reg <= (OTHERS => to_signed(0, 32));
      ELSIF enb = '1' THEN
        rd_64_reg(0) <= residual;
        rd_64_reg(1 TO 13) <= rd_64_reg(0 TO 12);
      END IF;
    END IF;
  END PROCESS rd_64_process;

  residual_1 <= rd_64_reg(13);

  p105_output : PROCESS (Cd_t, P_pred, c_15)
    VARIABLE c16 : signed(64 DOWNTO 0);
    VARIABLE add_cast : signed(65 DOWNTO 0);
    VARIABLE mul_temp : signed(63 DOWNTO 0);
    VARIABLE add_cast_0 : signed(65 DOWNTO 0);
    VARIABLE add_temp : signed(65 DOWNTO 0);
  BEGIN
    c16 := to_signed(0, 65);
    mul_temp := to_signed(0, 64);
    add_temp := to_signed(0, 66);
    add_cast := to_signed(0, 66);
    add_cast_0 := to_signed(0, 66);

    FOR l IN 0 TO 1 LOOP
      c16 := c_15(l);

      FOR k1 IN 0 TO 1 LOOP
        add_cast := resize(c16, 66);
        mul_temp := P_pred(l, k1) * Cd_t(k1);
        add_cast_0 := resize(mul_temp, 66);
        add_temp := add_cast + add_cast_0;
        IF (add_temp(65) = '0') AND (add_temp(64) /= '0') THEN 
          c16 := "01111111111111111111111111111111111111111111111111111111111111111";
        ELSIF (add_temp(65) = '1') AND (add_temp(64) /= '1') THEN 
          c16 := "10000000000000000000000000000000000000000000000000000000000000000";
        ELSE 
          c16 := add_temp(64 DOWNTO 0);
        END IF;
      END LOOP;

      c_17(l) <= c16;
    END LOOP;

  END PROCESS p105_output;


  rd_38_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rd_38_reg <= (OTHERS => to_signed(0, 65));
      ELSIF enb = '1' THEN
        rd_38_reg(0 TO 1) <= c_17(0 TO 1);
        rd_38_reg(2 TO 33) <= rd_38_reg(0 TO 31);
      END IF;
    END IF;
  END PROCESS rd_38_process;

  c_18(0 TO 1) <= rd_38_reg(32 TO 33);

  p104_output : PROCESS (S_k, c_18)
    VARIABLE varargout_1 : signed(64 DOWNTO 0);
    VARIABLE idx2 : signed(31 DOWNTO 0);
    VARIABLE div_temp : signed(64 DOWNTO 0);
    VARIABLE t_01 : signed(64 DOWNTO 0);
  BEGIN
    varargout_1 := to_signed(0, 65);
    idx2 := to_signed(0, 32);
    div_temp := to_signed(0, 65);
    t_01 := to_signed(0, 65);

    FOR k2 IN 0 TO 1 LOOP
      IF S_k = to_signed(0, 32) THEN 
        IF c_18(k2) < to_signed(0, 65) THEN 
          varargout_1 := signed'("10000000000000000000000000000000000000000000000000000000000000000");
        ELSE 
          varargout_1 := signed'("01111111111111111111111111111111111111111111111111111111111111111");
        END IF;
      ELSE 
        IF S_k < to_signed(0, 32) THEN 
          idx2 := to_signed(0, 32);
        ELSE 
          idx2 := S_k;
        END IF;
        IF c_18(k2)(64) = idx2(31) THEN 
          t_01 := C_divbyzero_p;
        ELSE 
          t_01 := C_divbyzero_n;
        END IF;
        IF idx2 = 0 THEN 
          div_temp := t_01;
        ELSE 
          div_temp := c_18(k2) / idx2;
        END IF;
        varargout_1 := div_temp;
      END IF;
      c_19(k2) <= varargout_1;
    END LOOP;

  END PROCESS p104_output;


  rd_39_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        c_20 <= (OTHERS => to_signed(0, 65));
      ELSIF enb = '1' THEN
        c_20 <= c_19;
      END IF;
    END IF;
  END PROCESS rd_39_process;



  K_1_gen: FOR ii3 IN 0 TO 1 GENERATE
    
    K_1(ii3) <= X"7FFFFFFF" WHEN (c_20(ii3)(64) = '0') AND (c_20(ii3)(63 DOWNTO 31) /= "000000000000000000000000000000000") ELSE
        X"80000000" WHEN (c_20(ii3)(64) = '1') AND (c_20(ii3)(63 DOWNTO 31) /= "111111111111111111111111111111111") ELSE
        c_20(ii3)(31 DOWNTO 0);
  END GENERATE K_1_gen;


  rd_40_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rd_40_reg <= (OTHERS => to_signed(0, 32));
      ELSIF enb = '1' THEN
        rd_40_reg(0 TO 1) <= K_1(0 TO 1);
        rd_40_reg(2 TO 3) <= rd_40_reg(0 TO 1);
      END IF;
    END IF;
  END PROCESS rd_40_process;

  K_2(0 TO 1) <= rd_40_reg(2 TO 3);

  alpha_cast <= resize(S_k_1, 33);
  alpha_cast_1 <=  - (alpha_cast);
  y <= alpha_cast_1(31 DOWNTO 0);

  rd_33_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        y_1 <= to_signed(0, 32);
      ELSIF enb = '1' THEN
        y_1 <= y;
      END IF;
    END IF;
  END PROCESS rd_33_process;


  rd_32_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        S_k_1 <= to_signed(0, 32);
      ELSIF enb = '1' THEN
        S_k_1 <= S_k;
      END IF;
    END IF;
  END PROCESS rd_32_process;


  rd_35_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        S_k_2 <= to_signed(0, 32);
      ELSIF enb = '1' THEN
        S_k_2 <= S_k_1;
      END IF;
    END IF;
  END PROCESS rd_35_process;


  rd_27_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        R_k_3 <= to_signed(0, 32);
      ELSIF enb = '1' THEN
        R_k_3 <= R_k_2;
      END IF;
    END IF;
  END PROCESS rd_27_process;


  
  R_k_4 <= '1' WHEN R_k_2 > to_signed(1310720, 32) ELSE
      '0';

  rd_22_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        R_k_5 <= '0';
      ELSIF enb = '1' THEN
        R_k_5 <= R_k_4;
      END IF;
    END IF;
  END PROCESS rd_22_process;


  
  R_k_6 <= R_k_3 WHEN R_k_5 = '0' ELSE
      R_k;

  rd_28_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        R_k_7 <= to_signed(0, 32);
      ELSIF enb = '1' THEN
        R_k_7 <= R_k_6;
      END IF;
    END IF;
  END PROCESS rd_28_process;


  alpha_cast_2 <= resize(residual_2, 33);
  alpha_cast_3 <=  - (alpha_cast_2);
  y_2 <= alpha_cast_3(31 DOWNTO 0);

  rd_14_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        y_3 <= to_signed(0, 32);
      ELSIF enb = '1' THEN
        y_3 <= y_2;
      END IF;
    END IF;
  END PROCESS rd_14_process;


  rd_13_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        residual_2 <= to_signed(0, 32);
      ELSIF enb = '1' THEN
        residual_2 <= residual_3;
      END IF;
    END IF;
  END PROCESS rd_13_process;


  rd_16_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        residual <= to_signed(0, 32);
      ELSIF enb = '1' THEN
        residual <= residual_2;
      END IF;
    END IF;
  END PROCESS rd_16_process;


  p128_output : PROCESS (Cd, c_12, x_pred)
    VARIABLE c24 : signed(64 DOWNTO 0);
    VARIABLE add_cast1 : signed(65 DOWNTO 0);
    VARIABLE mul_temp1 : signed(63 DOWNTO 0);
    VARIABLE add_cast_01 : signed(65 DOWNTO 0);
    VARIABLE add_temp1 : signed(65 DOWNTO 0);
  BEGIN
    mul_temp1 := to_signed(0, 64);
    add_temp1 := to_signed(0, 66);
    add_cast1 := to_signed(0, 66);
    add_cast_01 := to_signed(0, 66);
    c24 := c_12;

    FOR k3 IN 0 TO 1 LOOP
      add_cast1 := resize(c24, 66);
      mul_temp1 := Cd(k3) * x_pred(k3);
      add_cast_01 := resize(mul_temp1, 66);
      add_temp1 := add_cast1 + add_cast_01;
      IF (add_temp1(65) = '0') AND (add_temp1(64) /= '0') THEN 
        c24 := "01111111111111111111111111111111111111111111111111111111111111111";
      ELSIF (add_temp1(65) = '1') AND (add_temp1(64) /= '1') THEN 
        c24 := "10000000000000000000000000000000000000000000000000000000000000000";
      ELSE 
        c24 := add_temp1(64 DOWNTO 0);
      END IF;
    END LOOP;

    c_25 <= c24;
  END PROCESS p128_output;


  rd_9_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        c_26 <= to_signed(0, 65);
      ELSIF enb = '1' THEN
        c_26 <= c_25;
      END IF;
    END IF;
  END PROCESS rd_9_process;


  
  y_pred <= X"7FFFFFFF" WHEN (c_26(64) = '0') AND (c_26(63 DOWNTO 47) /= "00000000000000000") ELSE
      X"80000000" WHEN (c_26(64) = '1') AND (c_26(63 DOWNTO 47) /= "11111111111111111") ELSE
      c_26(47 DOWNTO 16) + ('0' & (c_26(64) AND (c_26(15) OR c_26(14) OR c_26(13) OR c_26(12) OR c_26(11) OR c_26(10) OR c_26(9) OR c_26(8) OR c_26(7) OR c_26(6) OR c_26(5) OR c_26(4) OR c_26(3) OR c_26(2) OR c_26(1) OR c_26(0))));

  rd_10_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        y_pred_1 <= to_signed(0, 32);
      ELSIF enb = '1' THEN
        y_pred_1 <= y_pred;
      END IF;
    END IF;
  END PROCESS rd_10_process;


  tmp_16 <= resize(y_pred_1, 33);

  rd_11_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        tmp_17 <= to_signed(0, 33);
      ELSIF enb = '1' THEN
        tmp_17 <= tmp_16;
      END IF;
    END IF;
  END PROCESS rd_11_process;


  adder_sub_cast <= resize(tmp_15, 34);
  adder_sub_cast_1 <= resize(tmp_17, 34);
  adder_sub_temp <= adder_sub_cast - adder_sub_cast_1;
  
  tmp_18 <= "011111111111111111111111111111111" WHEN (adder_sub_temp(33) = '0') AND (adder_sub_temp(32) /= '0') ELSE
      "100000000000000000000000000000000" WHEN (adder_sub_temp(33) = '1') AND (adder_sub_temp(32) /= '1') ELSE
      adder_sub_temp(32 DOWNTO 0);

  rd_12_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        tmp_19 <= to_signed(0, 33);
      ELSIF enb = '1' THEN
        tmp_19 <= tmp_18;
      END IF;
    END IF;
  END PROCESS rd_12_process;


  
  residual_3 <= X"7FFFFFFF" WHEN (tmp_19(32) = '0') AND (tmp_19(31) /= '0') ELSE
      X"80000000" WHEN (tmp_19(32) = '1') AND (tmp_19(31) /= '1') ELSE
      tmp_19(31 DOWNTO 0);

  
  residual_4 <= '1' WHEN residual_3 < to_signed(0, 32) ELSE
      '0';

  rd_15_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rd_15_reg <= (OTHERS => '0');
      ELSIF enb = '1' THEN
        rd_15_reg(0) <= residual_4;
        rd_15_reg(1) <= rd_15_reg(0);
      END IF;
    END IF;
  END PROCESS rd_15_process;

  residual_5 <= rd_15_reg(1);

  
  y_4 <= residual WHEN residual_5 = '0' ELSE
      y_3;

  rd_17_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        y_5 <= to_signed(0, 32);
      ELSIF enb = '1' THEN
        y_5 <= y_4;
      END IF;
    END IF;
  END PROCESS rd_17_process;


  tmp_20 <= alpha * y_5;

  rd_18_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        tmp_21 <= to_signed(0, 64);
      ELSIF enb = '1' THEN
        tmp_21 <= tmp_20;
      END IF;
    END IF;
  END PROCESS rd_18_process;


  
  tmp_22 <= X"7FFFFFFF" WHEN (tmp_21(63) = '0') AND (tmp_21(62 DOWNTO 47) /= X"0000") ELSE
      X"80000000" WHEN (tmp_21(63) = '1') AND (tmp_21(62 DOWNTO 47) /= X"FFFF") ELSE
      tmp_21(47 DOWNTO 16) + ('0' & (tmp_21(63) AND (tmp_21(15) OR tmp_21(14) OR tmp_21(13) OR tmp_21(12) OR tmp_21(11) OR tmp_21(10) OR tmp_21(9) OR tmp_21(8) OR tmp_21(7) OR tmp_21(6) OR tmp_21(5) OR tmp_21(4) OR tmp_21(3) OR tmp_21(2) OR tmp_21(1) OR tmp_21(0))));

  rd_19_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        tmp_23 <= to_signed(0, 32);
      ELSIF enb = '1' THEN
        tmp_23 <= tmp_22;
      END IF;
    END IF;
  END PROCESS rd_19_process;


  tmp_24 <= resize(tmp_23, 33);

  rd_20_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        tmp_25 <= to_signed(0, 33);
      ELSIF enb = '1' THEN
        tmp_25 <= tmp_24;
      END IF;
    END IF;
  END PROCESS rd_20_process;


  adder_add_cast <= resize(tmp_13, 34);
  adder_add_cast_1 <= resize(tmp_25, 34);
  adder_add_temp <= adder_add_cast + adder_add_cast_1;
  
  tmp_26 <= "011111111111111111111111111111111" WHEN (adder_add_temp(33) = '0') AND (adder_add_temp(32) /= '0') ELSE
      "100000000000000000000000000000000" WHEN (adder_add_temp(33) = '1') AND (adder_add_temp(32) /= '1') ELSE
      adder_add_temp(32 DOWNTO 0);

  rd_21_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        tmp_27 <= to_signed(0, 33);
      ELSIF enb = '1' THEN
        tmp_27 <= tmp_26;
      END IF;
    END IF;
  END PROCESS rd_21_process;


  
  R_k_2 <= X"7FFFFFFF" WHEN (tmp_27(32) = '0') AND (tmp_27(31) /= '0') ELSE
      X"80000000" WHEN (tmp_27(32) = '1') AND (tmp_27(31) /= '1') ELSE
      tmp_27(31 DOWNTO 0);

  
  R_k_8 <= '1' WHEN R_k_2 < to_signed(6553, 32) ELSE
      '0';

  rd_26_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rd_26_reg <= (OTHERS => '0');
      ELSIF enb = '1' THEN
        rd_26_reg(0) <= R_k_8;
        rd_26_reg(1) <= rd_26_reg(0);
      END IF;
    END IF;
  END PROCESS rd_26_process;

  R_k_9 <= rd_26_reg(1);

  
  R_k_10 <= R_k_7 WHEN R_k_9 = '0' ELSE
      R_k_1;

  rd_29_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        R_k_11 <= to_signed(0, 32);
      ELSIF enb = '1' THEN
        R_k_11 <= R_k_10;
      END IF;
    END IF;
  END PROCESS rd_29_process;


  tmp_28 <= resize(R_k_11, 33);

  rd_30_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        tmp_29 <= to_signed(0, 33);
      ELSIF enb = '1' THEN
        tmp_29 <= tmp_28;
      END IF;
    END IF;
  END PROCESS rd_30_process;


  
  P_1 <= '1' WHEN P(1, 1) < to_signed(6, 32) ELSE
      '0';

  rd_58_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        P_2 <= '0';
      ELSIF enb = '1' THEN
        P_2 <= P_1;
      END IF;
    END IF;
  END PROCESS rd_58_process;


  
  sel_2 <= sel_1 WHEN P_2 = '0' ELSE
      s_1;

  rd_59_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sel_2_1 <= '0';
      ELSIF enb = '1' THEN
        sel_2_1 <= sel_2;
      END IF;
    END IF;
  END PROCESS rd_59_process;


  
  tmp_30 <= tmp_10 WHEN sel_2_1 = '0' ELSE
      tmp_11;

  rd_60_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        tmp_31 <= to_signed(0, 32);
      ELSIF enb = '1' THEN
        tmp_31 <= tmp_30;
      END IF;
    END IF;
  END PROCESS rd_60_process;


  
  P_4 <= '1' WHEN P_3(0, 0) < to_signed(6, 32) ELSE
      '0';

  rd_54_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        P_5 <= '0';
      ELSIF enb = '1' THEN
        P_5 <= P_4;
      END IF;
    END IF;
  END PROCESS rd_54_process;


  
  sel_2_2 <= sel WHEN P_5 = '0' ELSE
      s;

  rd_55_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sel_2_3 <= '0';
      ELSIF enb = '1' THEN
        sel_2_3 <= sel_2_2;
      END IF;
    END IF;
  END PROCESS rd_55_process;


  
  tmp_32 <= tmp_6 WHEN sel_2_3 = '0' ELSE
      tmp_7;

  rd_56_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        tmp_33 <= to_signed(0, 32);
      ELSIF enb = '1' THEN
        tmp_33 <= tmp_32;
      END IF;
    END IF;
  END PROCESS rd_56_process;


  tmp_34 <= P_6(1, 0);

  rd_50_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        tmp_35 <= to_signed(0, 32);
      ELSIF enb = '1' THEN
        tmp_35 <= tmp_34;
      END IF;
    END IF;
  END PROCESS rd_50_process;


  tmp_36 <= resize(tmp_35, 33);

  rd_51_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        tmp_37 <= to_signed(0, 33);
      ELSIF enb = '1' THEN
        tmp_37 <= tmp_36;
      END IF;
    END IF;
  END PROCESS rd_51_process;


  tmp_38 <= P_6(0, 1);

  rd_48_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        tmp_39 <= to_signed(0, 32);
      ELSIF enb = '1' THEN
        tmp_39 <= tmp_38;
      END IF;
    END IF;
  END PROCESS rd_48_process;


  tmp_40 <= resize(tmp_39, 33);

  rd_49_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        tmp_41 <= to_signed(0, 33);
      ELSIF enb = '1' THEN
        tmp_41 <= tmp_40;
      END IF;
    END IF;
  END PROCESS rd_49_process;


  adder_add_cast_2 <= resize(tmp_41, 34);
  adder_add_cast_3 <= resize(tmp_37, 34);
  adder_add_temp_1 <= adder_add_cast_2 + adder_add_cast_3;
  
  tmp_42 <= "011111111111111111111111111111111" WHEN (adder_add_temp_1(33) = '0') AND (adder_add_temp_1(32) /= '0') ELSE
      "100000000000000000000000000000000" WHEN (adder_add_temp_1(33) = '1') AND (adder_add_temp_1(32) /= '1') ELSE
      adder_add_temp_1(32 DOWNTO 0);

  p92tmp_cast <= tmp_42 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0';
  p92tmp_div_temp <= p92tmp_cast / signed'("010000000000000000000000000000000");
  
  tmp_43 <= "011111111111111111111111111111111" WHEN (p92tmp_div_temp(62) = '0') AND (p92tmp_div_temp(61 DOWNTO 32) /= "000000000000000000000000000000") ELSE
      "100000000000000000000000000000000" WHEN (p92tmp_div_temp(62) = '1') AND (p92tmp_div_temp(61 DOWNTO 32) /= "111111111111111111111111111111") ELSE
      p92tmp_div_temp(32 DOWNTO 0);

  rd_52_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        tmp_44 <= to_signed(0, 33);
      ELSIF enb = '1' THEN
        tmp_44 <= tmp_43;
      END IF;
    END IF;
  END PROCESS rd_52_process;


  
  P12 <= X"7FFFFFFF" WHEN (tmp_44(32) = '0') AND (tmp_44(31) /= '0') ELSE
      X"80000000" WHEN (tmp_44(32) = '1') AND (tmp_44(31) /= '1') ELSE
      tmp_44(31 DOWNTO 0);

  c1134_P_pred_gen1: FOR d1 IN 0 TO 1 GENERATE
    c1134_P_pred_gen: FOR d0 IN 0 TO 1 GENERATE
      c1134_P_pred(d0 + (d1 * 2)) <= P_pred(d0, d1);
    END GENERATE;
  END GENERATE;

  rd_45_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rd_45_reg <= (OTHERS => to_signed(0, 32));
      ELSIF enb = '1' THEN
        rd_45_reg(0 TO 3) <= c1134_P_pred(0 TO 3);
        rd_45_reg(4 TO 95) <= rd_45_reg(0 TO 91);
      END IF;
    END IF;
  END PROCESS rd_45_process;

  c1134_P_pred_1(0 TO 3) <= rd_45_reg(92 TO 95);

  P_pred_1_gen1: FOR d1 IN 0 TO 1 GENERATE
    P_pred_1_gen: FOR d0 IN 0 TO 1 GENERATE
      P_pred_1(d0, d1) <= c1134_P_pred_1(d0 + (d1 * 2));
    END GENERATE;
  END GENERATE;

  p99_output : PROCESS (Cd, K_3, c_8)
    VARIABLE c37 : matrix_of_signed64(0 TO 1, 0 TO 1);
    VARIABLE add_cast2 : signed(64 DOWNTO 0);
    VARIABLE mul_temp2 : signed(63 DOWNTO 0);
    VARIABLE add_cast_02 : signed(64 DOWNTO 0);
    VARIABLE add_temp2 : signed(64 DOWNTO 0);
  BEGIN
    mul_temp2 := to_signed(0, 64);
    add_temp2 := to_signed(0, 65);
    add_cast2 := to_signed(0, 65);
    add_cast_02 := to_signed(0, 65);
    c37 := c_8;

    FOR l1 IN 0 TO 1 LOOP
      FOR m IN 0 TO 1 LOOP
        add_cast2 := resize(c37(l1, m), 65);
        mul_temp2 := K_3(l1) * Cd(m);
        add_cast_02 := resize(mul_temp2, 65);
        add_temp2 := add_cast2 + add_cast_02;
        IF (add_temp2(64) = '0') AND (add_temp2(63) /= '0') THEN 
          c37(l1, m) := X"7FFFFFFFFFFFFFFF";
        ELSIF (add_temp2(64) = '1') AND (add_temp2(63) /= '1') THEN 
          c37(l1, m) := X"8000000000000000";
        ELSE 
          c37(l1, m) := add_temp2(63 DOWNTO 0);
        END IF;
      END LOOP;
    END LOOP;

    c_38 <= c37;
  END PROCESS p99_output;


  c76_c_gen1: FOR d1 IN 0 TO 1 GENERATE
    c76_c_gen: FOR d0 IN 0 TO 1 GENERATE
      c76_c(d0 + (d1 * 2)) <= c_38(d0, d1);
    END GENERATE;
  END GENERATE;

  rd_41_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        c76_c_1 <= (OTHERS => to_signed(0, 64));
      ELSIF enb = '1' THEN
        c76_c_1 <= c76_c;
      END IF;
    END IF;
  END PROCESS rd_41_process;



  c77_tmp_gen: FOR ii4 IN 0 TO 3 GENERATE
    
    c77_tmp(ii4) <= X"7FFFFFFF" WHEN (c76_c_1(ii4)(63) = '0') AND (c76_c_1(ii4)(62 DOWNTO 47) /= X"0000") ELSE
        X"80000000" WHEN (c76_c_1(ii4)(63) = '1') AND (c76_c_1(ii4)(62 DOWNTO 47) /= X"FFFF") ELSE
        c76_c_1(ii4)(47 DOWNTO 16) + ('0' & (c76_c_1(ii4)(63) AND (c76_c_1(ii4)(15) OR c76_c_1(ii4)(14) OR c76_c_1(ii4)(13) OR c76_c_1(ii4)(12) OR c76_c_1(ii4)(11) OR c76_c_1(ii4)(10) OR c76_c_1(ii4)(9) OR c76_c_1(ii4)(8) OR c76_c_1(ii4)(7) OR c76_c_1(ii4)(6) OR c76_c_1(ii4)(5) OR c76_c_1(ii4)(4) OR c76_c_1(ii4)(3) OR c76_c_1(ii4)(2) OR c76_c_1(ii4)(1) OR c76_c_1(ii4)(0))));
  END GENERATE c77_tmp_gen;


  rd_42_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        c77_tmp_1 <= (OTHERS => to_signed(0, 32));
      ELSIF enb = '1' THEN
        c77_tmp_1 <= c77_tmp;
      END IF;
    END IF;
  END PROCESS rd_42_process;



  c78_tmp_gen: FOR ii5 IN 0 TO 3 GENERATE
    c78_tmp(ii5) <= resize(c77_tmp_1(ii5), 33);
  END GENERATE c78_tmp_gen;


  rd_43_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        c78_tmp_1 <= (OTHERS => to_signed(0, 33));
      ELSIF enb = '1' THEN
        c78_tmp_1 <= c78_tmp;
      END IF;
    END IF;
  END PROCESS rd_43_process;



  c79_tmp_1_gen: FOR t_02 IN 0 TO 3 GENERATE
    adder_sub_cast_2(t_02) <= resize(c79_tmp(t_02), 34);
    adder_sub_cast_3(t_02) <= resize(c78_tmp_1(t_02), 34);
    adder_sub_temp_1(t_02) <= adder_sub_cast_2(t_02) - adder_sub_cast_3(t_02);
    
    c79_tmp_1(t_02) <= "011111111111111111111111111111111" WHEN (adder_sub_temp_1(t_02)(33) = '0') AND (adder_sub_temp_1(t_02)(32) /= '0') ELSE
        "100000000000000000000000000000000" WHEN (adder_sub_temp_1(t_02)(33) = '1') AND (adder_sub_temp_1(t_02)(32) /= '1') ELSE
        adder_sub_temp_1(t_02)(32 DOWNTO 0);
  END GENERATE c79_tmp_1_gen;


  rd_44_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        c79_tmp_2 <= (OTHERS => to_signed(0, 33));
      ELSIF enb = '1' THEN
        c79_tmp_2 <= c79_tmp_1;
      END IF;
    END IF;
  END PROCESS rd_44_process;



  c81_a0_gen: FOR ii6 IN 0 TO 3 GENERATE
    
    c81_a0(ii6) <= X"7FFFFFFF" WHEN (c79_tmp_2(ii6)(32) = '0') AND (c79_tmp_2(ii6)(31) /= '0') ELSE
        X"80000000" WHEN (c79_tmp_2(ii6)(32) = '1') AND (c79_tmp_2(ii6)(31) /= '1') ELSE
        c79_tmp_2(ii6)(31 DOWNTO 0);
  END GENERATE c81_a0_gen;


  a0_gen1: FOR d1 IN 0 TO 1 GENERATE
    a0_gen: FOR d0 IN 0 TO 1 GENERATE
      a0(d0, d1) <= c81_a0(d0 + (d1 * 2));
    END GENERATE;
  END GENERATE;

  p96_output : PROCESS (P_pred_1, a0, c_6)
    VARIABLE c42 : matrix_of_signed65(0 TO 1, 0 TO 1);
    VARIABLE c_0 : signed(64 DOWNTO 0);
    VARIABLE add_cast3 : signed(65 DOWNTO 0);
    VARIABLE mul_temp3 : signed(63 DOWNTO 0);
    VARIABLE add_cast_03 : signed(65 DOWNTO 0);
    VARIABLE add_temp3 : signed(65 DOWNTO 0);
  BEGIN
    c_0 := to_signed(0, 65);
    mul_temp3 := to_signed(0, 64);
    add_temp3 := to_signed(0, 66);
    add_cast3 := to_signed(0, 66);
    add_cast_03 := to_signed(0, 66);
    c42 := c_6;

    FOR l2 IN 0 TO 1 LOOP
      FOR m1 IN 0 TO 1 LOOP
        c_0 := c42(l2, m1);

        FOR k4 IN 0 TO 1 LOOP
          add_cast3 := resize(c_0, 66);
          mul_temp3 := a0(l2, k4) * P_pred_1(k4, m1);
          add_cast_03 := resize(mul_temp3, 66);
          add_temp3 := add_cast3 + add_cast_03;
          IF (add_temp3(65) = '0') AND (add_temp3(64) /= '0') THEN 
            c_0 := "01111111111111111111111111111111111111111111111111111111111111111";
          ELSIF (add_temp3(65) = '1') AND (add_temp3(64) /= '1') THEN 
            c_0 := "10000000000000000000000000000000000000000000000000000000000000000";
          ELSE 
            c_0 := add_temp3(64 DOWNTO 0);
          END IF;
        END LOOP;

        c42(l2, m1) := c_0;
      END LOOP;
    END LOOP;

    c_43 <= c42;
  END PROCESS p96_output;


  c85_c_gen1: FOR d1 IN 0 TO 1 GENERATE
    c85_c_gen: FOR d0 IN 0 TO 1 GENERATE
      c85_c(d0 + (d1 * 2)) <= c_43(d0, d1);
    END GENERATE;
  END GENERATE;

  rd_46_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        c85_c_1 <= (OTHERS => to_signed(0, 65));
      ELSIF enb = '1' THEN
        c85_c_1 <= c85_c;
      END IF;
    END IF;
  END PROCESS rd_46_process;



  c65_P_gen: FOR ii7 IN 0 TO 3 GENERATE
    
    c65_P(ii7) <= X"7FFFFFFF" WHEN (c85_c_1(ii7)(64) = '0') AND (c85_c_1(ii7)(63 DOWNTO 47) /= "00000000000000000") ELSE
        X"80000000" WHEN (c85_c_1(ii7)(64) = '1') AND (c85_c_1(ii7)(63 DOWNTO 47) /= "11111111111111111") ELSE
        c85_c_1(ii7)(47 DOWNTO 16) + ('0' & (c85_c_1(ii7)(64) AND (c85_c_1(ii7)(15) OR c85_c_1(ii7)(14) OR c85_c_1(ii7)(13) OR c85_c_1(ii7)(12) OR c85_c_1(ii7)(11) OR c85_c_1(ii7)(10) OR c85_c_1(ii7)(9) OR c85_c_1(ii7)(8) OR c85_c_1(ii7)(7) OR c85_c_1(ii7)(6) OR c85_c_1(ii7)(5) OR c85_c_1(ii7)(4) OR c85_c_1(ii7)(3) OR c85_c_1(ii7)(2) OR c85_c_1(ii7)(1) OR c85_c_1(ii7)(0))));
  END GENERATE c65_P_gen;


  P_6_gen1: FOR d1 IN 0 TO 1 GENERATE
    P_6_gen: FOR d0 IN 0 TO 1 GENERATE
      P_6(d0, d1) <= c65_P(d0 + (d1 * 2));
    END GENERATE;
  END GENERATE;

  c1118_P_gen1: FOR d1 IN 0 TO 1 GENERATE
    c1118_P_gen: FOR d0 IN 0 TO 1 GENERATE
      c1118_P(d0 + (d1 * 2)) <= P_6(d0, d1);
    END GENERATE;
  END GENERATE;

  rd_47_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rd_47_reg <= (OTHERS => to_signed(0, 32));
      ELSIF enb = '1' THEN
        rd_47_reg(0 TO 3) <= c1118_P(0 TO 3);
        rd_47_reg(4 TO 11) <= rd_47_reg(0 TO 7);
      END IF;
    END IF;
  END PROCESS rd_47_process;

  c1118_P_1(0 TO 3) <= rd_47_reg(8 TO 11);

  P_7_gen1: FOR d1 IN 0 TO 1 GENERATE
    P_7_gen: FOR d0 IN 0 TO 1 GENERATE
      P_7(d0, d1) <= c1118_P_1(d0 + (d1 * 2));
    END GENERATE;
  END GENERATE;

  p91P_output : PROCESS (P12, P_7)
  BEGIN
    P_3 <= P_7;
    P_3(0, 1) <= P12;
    P_3(1, 0) <= P12;
  END PROCESS p91P_output;


  c1120_P_gen1: FOR d1 IN 0 TO 1 GENERATE
    c1120_P_gen: FOR d0 IN 0 TO 1 GENERATE
      c1120_P(d0 + (d1 * 2)) <= P_3(d0, d1);
    END GENERATE;
  END GENERATE;

  rd_53_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rd_53_reg <= (OTHERS => to_signed(0, 32));
      ELSIF enb = '1' THEN
        rd_53_reg(0 TO 3) <= c1120_P(0 TO 3);
        rd_53_reg(4 TO 11) <= rd_53_reg(0 TO 7);
      END IF;
    END IF;
  END PROCESS rd_53_process;

  c1120_P_1(0 TO 3) <= rd_53_reg(8 TO 11);

  P_8_gen1: FOR d1 IN 0 TO 1 GENERATE
    P_8_gen: FOR d0 IN 0 TO 1 GENERATE
      P_8(d0, d1) <= c1120_P_1(d0 + (d1 * 2));
    END GENERATE;
  END GENERATE;

  Assignment_output : PROCESS (P_8, tmp_33, tmp_5, tmp_8)
  BEGIN

    FOR jj IN 0 TO 1 LOOP
      FOR ii8 IN 0 TO 1 LOOP
        IF (tmp_33 = to_signed(ii8, 32)) AND (tmp_8 = to_signed(jj, 32)) THEN 
          P(ii8, jj) <= tmp_5;
        ELSE 
          P(ii8, jj) <= P_8(ii8, jj);
        END IF;
      END LOOP;
    END LOOP;

  END PROCESS Assignment_output;


  c1116_P_gen1: FOR d1 IN 0 TO 1 GENERATE
    c1116_P_gen: FOR d0 IN 0 TO 1 GENERATE
      c1116_P(d0 + (d1 * 2)) <= P(d0, d1);
    END GENERATE;
  END GENERATE;

  rd_57_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rd_57_reg <= (OTHERS => to_signed(0, 32));
      ELSIF enb = '1' THEN
        rd_57_reg(0 TO 3) <= c1116_P(0 TO 3);
        rd_57_reg(4 TO 11) <= rd_57_reg(0 TO 7);
      END IF;
    END IF;
  END PROCESS rd_57_process;

  c1116_P_1(0 TO 3) <= rd_57_reg(8 TO 11);

  P_9_gen1: FOR d1 IN 0 TO 1 GENERATE
    P_9_gen: FOR d0 IN 0 TO 1 GENERATE
      P_9(d0, d1) <= c1116_P_1(d0 + (d1 * 2));
    END GENERATE;
  END GENERATE;

  Assignment_1_output : PROCESS (P_9, tmp_12, tmp_31, tmp_9)
  BEGIN

    FOR jj1 IN 0 TO 1 LOOP
      FOR ii9 IN 0 TO 1 LOOP
        IF (tmp_31 = to_signed(ii9, 32)) AND (tmp_12 = to_signed(jj1, 32)) THEN 
          P_10(ii9, jj1) <= tmp_9;
        ELSE 
          P_10(ii9, jj1) <= P_9(ii9, jj1);
        END IF;
      END LOOP;
    END LOOP;

  END PROCESS Assignment_1_output;


  c1143_P_gen1: FOR d1 IN 0 TO 1 GENERATE
    c1143_P_gen: FOR d0 IN 0 TO 1 GENERATE
      c1143_P(d0 + (d1 * 2)) <= P_10(d0, d1);
    END GENERATE;
  END GENERATE;

  crp_out_delay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        c1143_P_1 <= (OTHERS => to_signed(0, 32));
      ELSIF enb = '1' THEN
        c1143_P_1 <= c1143_P;
      END IF;
    END IF;
  END PROCESS crp_out_delay_process;


  P_11_gen1: FOR d1 IN 0 TO 1 GENERATE
    P_11_gen: FOR d0 IN 0 TO 1 GENERATE
      P_11(d0, d1) <= c1143_P_1(d0 + (d1 * 2));
    END GENERATE;
  END GENERATE;

  c1143_P_2_gen1: FOR d1 IN 0 TO 1 GENERATE
    c1143_P_2_gen: FOR d0 IN 0 TO 1 GENERATE
      c1143_P_2(d0 + (d1 * 2)) <= P_11(d0, d1);
    END GENERATE;
  END GENERATE;

  P_reg_bypass_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        P_reg_bypass_reg <= (OTHERS => to_signed(0, 32));
      ELSIF enb_1_1000000_1 = '1' THEN
        P_reg_bypass_reg <= c1143_P_2;
      END IF;
    END IF;
  END PROCESS P_reg_bypass_process;

  
  P_12 <= c1143_P_2 WHEN enb_1_1000000_1 = '1' ELSE
      P_reg_bypass_reg;

  P_reg_out_gen1: FOR d1 IN 0 TO 1 GENERATE
    P_reg_out_gen: FOR d0 IN 0 TO 1 GENERATE
      P_reg_out(d0, d1) <= P_12(d0 + (d1 * 2));
    END GENERATE;
  END GENERATE;

  c318_P_reg_out_gen1: FOR d1 IN 0 TO 1 GENERATE
    c318_P_reg_out_gen: FOR d0 IN 0 TO 1 GENERATE
      c318_P_reg_out(d0 + (d1 * 2)) <= P_reg_out(d0, d1);
    END GENERATE;
  END GENERATE;

  
  c318_P <= c318_P_reg_Initial_Val_out WHEN P_reg_ctrl_delay_out = '0' ELSE
      c318_P_reg_out;

  P_13_gen1: FOR d1 IN 0 TO 1 GENERATE
    P_13_gen: FOR d0 IN 0 TO 1 GENERATE
      P_13(d0, d1) <= c318_P(d0 + (d1 * 2));
    END GENERATE;
  END GENERATE;

  c886_P_gen1: FOR d1 IN 0 TO 1 GENERATE
    c886_P_gen: FOR d0 IN 0 TO 1 GENERATE
      c886_P(d0 + (d1 * 2)) <= P_13(d0, d1);
    END GENERATE;
  END GENERATE;

  c934_P <= c886_P;

  P_14_gen1: FOR d1 IN 0 TO 1 GENERATE
    P_14_gen: FOR d0 IN 0 TO 1 GENERATE
      P_14(d0, d1) <= c934_P(d0 + (d1 * 2));
    END GENERATE;
  END GENERATE;

  c1136_P_gen1: FOR d1 IN 0 TO 1 GENERATE
    c1136_P_gen: FOR d0 IN 0 TO 1 GENERATE
      c1136_P(d0 + (d1 * 2)) <= P_14(d0, d1);
    END GENERATE;
  END GENERATE;

  rd_0_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        c1136_P_1 <= (OTHERS => to_signed(0, 32));
      ELSIF enb = '1' THEN
        c1136_P_1 <= c1136_P;
      END IF;
    END IF;
  END PROCESS rd_0_1_process;


  P_15_gen1: FOR d1 IN 0 TO 1 GENERATE
    P_15_gen: FOR d0 IN 0 TO 1 GENERATE
      P_15(d0, d1) <= c1136_P_1(d0 + (d1 * 2));
    END GENERATE;
  END GENERATE;

  p134_output : PROCESS (Ad, P_15, c_5)
    VARIABLE c45 : matrix_of_signed65(0 TO 1, 0 TO 1);
    VARIABLE c_01 : signed(64 DOWNTO 0);
    VARIABLE add_cast4 : signed(65 DOWNTO 0);
    VARIABLE mul_temp4 : signed(63 DOWNTO 0);
    VARIABLE add_cast_04 : signed(65 DOWNTO 0);
    VARIABLE add_temp4 : signed(65 DOWNTO 0);
  BEGIN
    c_01 := to_signed(0, 65);
    mul_temp4 := to_signed(0, 64);
    add_temp4 := to_signed(0, 66);
    add_cast4 := to_signed(0, 66);
    add_cast_04 := to_signed(0, 66);
    c45 := c_5;

    FOR l3 IN 0 TO 1 LOOP
      FOR m2 IN 0 TO 1 LOOP
        c_01 := c45(l3, m2);

        FOR k5 IN 0 TO 1 LOOP
          add_cast4 := resize(c_01, 66);
          mul_temp4 := Ad(l3, k5) * P_15(k5, m2);
          add_cast_04 := resize(mul_temp4, 66);
          add_temp4 := add_cast4 + add_cast_04;
          IF (add_temp4(65) = '0') AND (add_temp4(64) /= '0') THEN 
            c_01 := "01111111111111111111111111111111111111111111111111111111111111111";
          ELSIF (add_temp4(65) = '1') AND (add_temp4(64) /= '1') THEN 
            c_01 := "10000000000000000000000000000000000000000000000000000000000000000";
          ELSE 
            c_01 := add_temp4(64 DOWNTO 0);
          END IF;
        END LOOP;

        c45(l3, m2) := c_01;
      END LOOP;
    END LOOP;

    c_46 <= c45;
  END PROCESS p134_output;


  c92_c_gen1: FOR d1 IN 0 TO 1 GENERATE
    c92_c_gen: FOR d0 IN 0 TO 1 GENERATE
      c92_c(d0 + (d1 * 2)) <= c_46(d0, d1);
    END GENERATE;
  END GENERATE;

  c_47_gen1: FOR d1 IN 0 TO 1 GENERATE
    c_47_gen: FOR d0 IN 0 TO 1 GENERATE
      c_47(d0, d1) <= c92_c(d0 + (d1 * 2));
    END GENERATE;
  END GENERATE;

  p131_output : PROCESS (Ad_t, c_4, c_47)
    VARIABLE c48 : matrix_of_signed98(0 TO 1, 0 TO 1);
    VARIABLE c_02 : signed(97 DOWNTO 0);
    VARIABLE add_cast5 : signed(98 DOWNTO 0);
    VARIABLE mul_temp5 : signed(96 DOWNTO 0);
    VARIABLE add_cast_05 : signed(98 DOWNTO 0);
    VARIABLE add_temp5 : signed(98 DOWNTO 0);
  BEGIN
    c_02 := to_signed(0, 98);
    mul_temp5 := to_signed(0, 97);
    add_temp5 := to_signed(0, 99);
    add_cast5 := to_signed(0, 99);
    add_cast_05 := to_signed(0, 99);
    c48 := c_4;

    FOR l4 IN 0 TO 1 LOOP
      FOR m3 IN 0 TO 1 LOOP
        c_02 := c48(l4, m3);

        FOR k6 IN 0 TO 1 LOOP
          add_cast5 := resize(c_02, 99);
          mul_temp5 := c_47(l4, k6) * Ad_t(k6, m3);
          add_cast_05 := resize(mul_temp5, 99);
          add_temp5 := add_cast5 + add_cast_05;
          IF (add_temp5(98) = '0') AND (add_temp5(97) /= '0') THEN 
            c_02 := "01111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111";
          ELSIF (add_temp5(98) = '1') AND (add_temp5(97) /= '1') THEN 
            c_02 := "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
          ELSE 
            c_02 := add_temp5(97 DOWNTO 0);
          END IF;
        END LOOP;

        c48(l4, m3) := c_02;
      END LOOP;
    END LOOP;

    c_49 <= c48;
  END PROCESS p131_output;


  c94_c_gen1: FOR d1 IN 0 TO 1 GENERATE
    c94_c_gen: FOR d0 IN 0 TO 1 GENERATE
      c94_c(d0 + (d1 * 2)) <= c_49(d0, d1);
    END GENERATE;
  END GENERATE;


  c95_tmp_gen: FOR ii10 IN 0 TO 3 GENERATE
    c95_tmp(ii10) <= resize(c94_c(ii10), 99);
  END GENERATE c95_tmp_gen;


  rd_1_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        c95_tmp_1 <= (OTHERS => to_signed(0, 99));
      ELSIF enb = '1' THEN
        c95_tmp_1 <= c95_tmp;
      END IF;
    END IF;
  END PROCESS rd_1_1_process;



  c96_tmp_gen: FOR t_03 IN 0 TO 3 GENERATE
    adder_add_cast_4(t_03) <= resize(c95_tmp_1(t_03), 100);
    adder_add_cast_5(t_03) <= resize(c3_tmp(t_03), 100);
    adder_add_temp_2(t_03) <= adder_add_cast_4(t_03) + adder_add_cast_5(t_03);
    
    c96_tmp(t_03) <= "011111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111" WHEN (adder_add_temp_2(t_03)(99) = '0') AND (adder_add_temp_2(t_03)(98) /= '0') ELSE
        "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000" WHEN (adder_add_temp_2(t_03)(99) = '1') AND (adder_add_temp_2(t_03)(98) /= '1') ELSE
        adder_add_temp_2(t_03)(98 DOWNTO 0);
  END GENERATE c96_tmp_gen;


  rd_2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        c96_tmp_1 <= (OTHERS => to_signed(0, 99));
      ELSIF enb = '1' THEN
        c96_tmp_1 <= c96_tmp;
      END IF;
    END IF;
  END PROCESS rd_2_process;



  c84_P_pred_gen: FOR ii11 IN 0 TO 3 GENERATE
    
    c84_P_pred(ii11) <= X"7FFFFFFF" WHEN (c96_tmp_1(ii11)(98) = '0') AND (c96_tmp_1(ii11)(97 DOWNTO 63) /= "00000000000000000000000000000000000") ELSE
        X"80000000" WHEN (c96_tmp_1(ii11)(98) = '1') AND (c96_tmp_1(ii11)(97 DOWNTO 63) /= "11111111111111111111111111111111111") ELSE
        c96_tmp_1(ii11)(63 DOWNTO 32) + ('0' & (c96_tmp_1(ii11)(98) AND (c96_tmp_1(ii11)(31) OR c96_tmp_1(ii11)(30) OR c96_tmp_1(ii11)(29) OR c96_tmp_1(ii11)(28) OR c96_tmp_1(ii11)(27) OR c96_tmp_1(ii11)(26) OR c96_tmp_1(ii11)(25) OR c96_tmp_1(ii11)(24) OR c96_tmp_1(ii11)(23) OR c96_tmp_1(ii11)(22) OR c96_tmp_1(ii11)(21) OR c96_tmp_1(ii11)(20) OR c96_tmp_1(ii11)(19) OR c96_tmp_1(ii11)(18) OR c96_tmp_1(ii11)(17) OR c96_tmp_1(ii11)(16) OR c96_tmp_1(ii11)(15) OR c96_tmp_1(ii11)(14) OR c96_tmp_1(ii11)(13) OR c96_tmp_1(ii11)(12) OR c96_tmp_1(ii11)(11) OR c96_tmp_1(ii11)(10) OR c96_tmp_1(ii11)(9) OR c96_tmp_1(ii11)(8) OR c96_tmp_1(ii11)(7) OR c96_tmp_1(ii11)(6) OR c96_tmp_1(ii11)(5) OR c96_tmp_1(ii11)(4) OR c96_tmp_1(ii11)(3) OR c96_tmp_1(ii11)(2) OR c96_tmp_1(ii11)(1) OR c96_tmp_1(ii11)(0))));
  END GENERATE c84_P_pred_gen;


  P_pred_gen1: FOR d1 IN 0 TO 1 GENERATE
    P_pred_gen: FOR d0 IN 0 TO 1 GENERATE
      P_pred(d0, d1) <= c84_P_pred(d0 + (d1 * 2));
    END GENERATE;
  END GENERATE;

  p115_output : PROCESS (Cd, P_pred, c_3)
    VARIABLE c52 : signed(64 DOWNTO 0);
    VARIABLE add_cast6 : signed(65 DOWNTO 0);
    VARIABLE mul_temp6 : signed(63 DOWNTO 0);
    VARIABLE add_cast_06 : signed(65 DOWNTO 0);
    VARIABLE add_temp6 : signed(65 DOWNTO 0);
  BEGIN
    c52 := to_signed(0, 65);
    mul_temp6 := to_signed(0, 64);
    add_temp6 := to_signed(0, 66);
    add_cast6 := to_signed(0, 66);
    add_cast_06 := to_signed(0, 66);

    FOR m4 IN 0 TO 1 LOOP
      c52 := c_3(m4);

      FOR k7 IN 0 TO 1 LOOP
        add_cast6 := resize(c52, 66);
        mul_temp6 := Cd(k7) * P_pred(k7, m4);
        add_cast_06 := resize(mul_temp6, 66);
        add_temp6 := add_cast6 + add_cast_06;
        IF (add_temp6(65) = '0') AND (add_temp6(64) /= '0') THEN 
          c52 := "01111111111111111111111111111111111111111111111111111111111111111";
        ELSIF (add_temp6(65) = '1') AND (add_temp6(64) /= '1') THEN 
          c52 := "10000000000000000000000000000000000000000000000000000000000000000";
        ELSE 
          c52 := add_temp6(64 DOWNTO 0);
        END IF;
      END LOOP;

      c_53(m4) <= c52;
    END LOOP;

  END PROCESS p115_output;


  p112_output : PROCESS (Cd_t, c_2, c_53)
    VARIABLE c54 : signed(97 DOWNTO 0);
    VARIABLE add_cast7 : signed(98 DOWNTO 0);
    VARIABLE mul_temp7 : signed(96 DOWNTO 0);
    VARIABLE add_cast_07 : signed(98 DOWNTO 0);
    VARIABLE add_temp7 : signed(98 DOWNTO 0);
  BEGIN
    mul_temp7 := to_signed(0, 97);
    add_temp7 := to_signed(0, 99);
    add_cast7 := to_signed(0, 99);
    add_cast_07 := to_signed(0, 99);
    c54 := c_2;

    FOR k8 IN 0 TO 1 LOOP
      add_cast7 := resize(c54, 99);
      mul_temp7 := c_53(k8) * Cd_t(k8);
      add_cast_07 := resize(mul_temp7, 99);
      add_temp7 := add_cast7 + add_cast_07;
      IF (add_temp7(98) = '0') AND (add_temp7(97) /= '0') THEN 
        c54 := "01111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111";
      ELSIF (add_temp7(98) = '1') AND (add_temp7(97) /= '1') THEN 
        c54 := "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
      ELSE 
        c54 := add_temp7(97 DOWNTO 0);
      END IF;
    END LOOP;

    c_55 <= c54;
  END PROCESS p112_output;


  rd_23_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        c_56 <= to_signed(0, 98);
      ELSIF enb = '1' THEN
        c_56 <= c_55;
      END IF;
    END IF;
  END PROCESS rd_23_process;


  
  tmp_45 <= X"7FFFFFFF" WHEN (c_56(97) = '0') AND (c_56(96 DOWNTO 63) /= "0000000000000000000000000000000000") ELSE
      X"80000000" WHEN (c_56(97) = '1') AND (c_56(96 DOWNTO 63) /= "1111111111111111111111111111111111") ELSE
      c_56(63 DOWNTO 32) + ('0' & (c_56(97) AND (c_56(31) OR c_56(30) OR c_56(29) OR c_56(28) OR c_56(27) OR c_56(26) OR c_56(25) OR c_56(24) OR c_56(23) OR c_56(22) OR c_56(21) OR c_56(20) OR c_56(19) OR c_56(18) OR c_56(17) OR c_56(16) OR c_56(15) OR c_56(14) OR c_56(13) OR c_56(12) OR c_56(11) OR c_56(10) OR c_56(9) OR c_56(8) OR c_56(7) OR c_56(6) OR c_56(5) OR c_56(4) OR c_56(3) OR c_56(2) OR c_56(1) OR c_56(0))));

  rd_24_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        tmp_46 <= to_signed(0, 32);
      ELSIF enb = '1' THEN
        tmp_46 <= tmp_45;
      END IF;
    END IF;
  END PROCESS rd_24_process;


  tmp_47 <= resize(tmp_46, 33);

  rd_25_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rd_25_reg <= (OTHERS => to_signed(0, 33));
      ELSIF enb = '1' THEN
        rd_25_reg(0) <= tmp_47;
        rd_25_reg(1 TO 13) <= rd_25_reg(0 TO 12);
      END IF;
    END IF;
  END PROCESS rd_25_process;

  tmp_48 <= rd_25_reg(13);

  adder_add_cast_6 <= resize(tmp_48, 34);
  adder_add_cast_7 <= resize(tmp_29, 34);
  adder_add_temp_3 <= adder_add_cast_6 + adder_add_cast_7;
  
  tmp_49 <= "011111111111111111111111111111111" WHEN (adder_add_temp_3(33) = '0') AND (adder_add_temp_3(32) /= '0') ELSE
      "100000000000000000000000000000000" WHEN (adder_add_temp_3(33) = '1') AND (adder_add_temp_3(32) /= '1') ELSE
      adder_add_temp_3(32 DOWNTO 0);

  rd_31_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        tmp_50 <= to_signed(0, 33);
      ELSIF enb = '1' THEN
        tmp_50 <= tmp_49;
      END IF;
    END IF;
  END PROCESS rd_31_process;


  
  S_k <= X"7FFFFFFF" WHEN (tmp_50(32) = '0') AND (tmp_50(31) /= '0') ELSE
      X"80000000" WHEN (tmp_50(32) = '1') AND (tmp_50(31) /= '1') ELSE
      tmp_50(31 DOWNTO 0);

  
  S_k_3 <= '1' WHEN S_k < to_signed(0, 32) ELSE
      '0';

  rd_34_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rd_34_reg <= (OTHERS => '0');
      ELSIF enb = '1' THEN
        rd_34_reg(0) <= S_k_3;
        rd_34_reg(1) <= rd_34_reg(0);
      END IF;
    END IF;
  END PROCESS rd_34_process;

  S_k_4 <= rd_34_reg(1);

  
  y_6 <= S_k_2 WHEN S_k_4 = '0' ELSE
      y_1;

  
  y_7 <= '1' WHEN y_6 < to_signed(65, 32) ELSE
      '0';

  rd_36_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        y_8 <= '0';
      ELSIF enb = '1' THEN
        y_8 <= y_7;
      END IF;
    END IF;
  END PROCESS rd_36_process;


  
  K_3 <= K_2 WHEN y_8 = '0' ELSE
      K;

  rd_63_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        K_9 <= (OTHERS => to_signed(0, 32));
      ELSIF enb = '1' THEN
        K_9 <= K_3;
      END IF;
    END IF;
  END PROCESS rd_63_process;



  tmp_51_gen: FOR t_04 IN 0 TO 1 GENERATE
    tmp_51(t_04) <= K_9(t_04) * residual_1;
  END GENERATE tmp_51_gen;


  rd_65_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        tmp_52 <= (OTHERS => to_signed(0, 64));
      ELSIF enb = '1' THEN
        tmp_52 <= tmp_51;
      END IF;
    END IF;
  END PROCESS rd_65_process;



  tmp_53_gen: FOR ii12 IN 0 TO 1 GENERATE
    
    tmp_53(ii12) <= X"7FFFFFFF" WHEN (tmp_52(ii12)(63) = '0') AND (tmp_52(ii12)(62 DOWNTO 47) /= X"0000") ELSE
        X"80000000" WHEN (tmp_52(ii12)(63) = '1') AND (tmp_52(ii12)(62 DOWNTO 47) /= X"FFFF") ELSE
        tmp_52(ii12)(47 DOWNTO 16) + ('0' & (tmp_52(ii12)(63) AND (tmp_52(ii12)(15) OR tmp_52(ii12)(14) OR tmp_52(ii12)(13) OR tmp_52(ii12)(12) OR tmp_52(ii12)(11) OR tmp_52(ii12)(10) OR tmp_52(ii12)(9) OR tmp_52(ii12)(8) OR tmp_52(ii12)(7) OR tmp_52(ii12)(6) OR tmp_52(ii12)(5) OR tmp_52(ii12)(4) OR tmp_52(ii12)(3) OR tmp_52(ii12)(2) OR tmp_52(ii12)(1) OR tmp_52(ii12)(0))));
  END GENERATE tmp_53_gen;


  rd_66_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        tmp_54 <= (OTHERS => to_signed(0, 32));
      ELSIF enb = '1' THEN
        tmp_54 <= tmp_53;
      END IF;
    END IF;
  END PROCESS rd_66_process;



  tmp_55_gen: FOR ii13 IN 0 TO 1 GENERATE
    tmp_55(ii13) <= resize(tmp_54(ii13), 33);
  END GENERATE tmp_55_gen;


  rd_67_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        tmp_56 <= (OTHERS => to_signed(0, 33));
      ELSIF enb = '1' THEN
        tmp_56 <= tmp_55;
      END IF;
    END IF;
  END PROCESS rd_67_process;


  crp_out_delay_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        x_est <= (OTHERS => to_signed(0, 32));
      ELSIF enb = '1' THEN
        x_est <= tmp_57;
      END IF;
    END IF;
  END PROCESS crp_out_delay_1_process;


  x_est_reg_bypass_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        x_est_reg_bypass_reg <= (OTHERS => to_signed(0, 32));
      ELSIF enb_1_1000000_1 = '1' THEN
        x_est_reg_bypass_reg <= x_est;
      END IF;
    END IF;
  END PROCESS x_est_reg_bypass_process;

  
  x_est_1 <= x_est WHEN enb_1_1000000_1 = '1' ELSE
      x_est_reg_bypass_reg;

  x_est_2 <= x_est_1;

  rd_3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        x_est_3 <= (OTHERS => to_signed(0, 32));
      ELSIF enb = '1' THEN
        x_est_3 <= x_est_2;
      END IF;
    END IF;
  END PROCESS rd_3_process;


  p137_output : PROCESS (Ad, c, x_est_3)
    VARIABLE c62 : signed(64 DOWNTO 0);
    VARIABLE add_cast8 : signed(65 DOWNTO 0);
    VARIABLE mul_temp8 : signed(63 DOWNTO 0);
    VARIABLE add_cast_08 : signed(65 DOWNTO 0);
    VARIABLE add_temp8 : signed(65 DOWNTO 0);
  BEGIN
    c62 := to_signed(0, 65);
    mul_temp8 := to_signed(0, 64);
    add_temp8 := to_signed(0, 66);
    add_cast8 := to_signed(0, 66);
    add_cast_08 := to_signed(0, 66);

    FOR l5 IN 0 TO 1 LOOP
      c62 := c(l5);

      FOR k10 IN 0 TO 1 LOOP
        add_cast8 := resize(c62, 66);
        mul_temp8 := Ad(l5, k10) * x_est_3(k10);
        add_cast_08 := resize(mul_temp8, 66);
        add_temp8 := add_cast8 + add_cast_08;
        IF (add_temp8(65) = '0') AND (add_temp8(64) /= '0') THEN 
          c62 := "01111111111111111111111111111111111111111111111111111111111111111";
        ELSIF (add_temp8(65) = '1') AND (add_temp8(64) /= '1') THEN 
          c62 := "10000000000000000000000000000000000000000000000000000000000000000";
        ELSE 
          c62 := add_temp8(64 DOWNTO 0);
        END IF;
      END LOOP;

      c_63(l5) <= c62;
    END LOOP;

  END PROCESS p137_output;



  tmp_58_gen: FOR ii14 IN 0 TO 1 GENERATE
    tmp_58(ii14) <= resize(c_63(ii14), 66);
  END GENERATE tmp_58_gen;


  rd_4_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rd_4_reg <= (OTHERS => to_signed(0, 66));
      ELSIF enb = '1' THEN
        rd_4_reg(0 TO 1) <= tmp_58(0 TO 1);
        rd_4_reg(2 TO 3) <= rd_4_reg(0 TO 1);
      END IF;
    END IF;
  END PROCESS rd_4_process;

  tmp_59(0 TO 1) <= rd_4_reg(2 TO 3);


  tmp_60_gen: FOR t_05 IN 0 TO 1 GENERATE
    adder_add_cast_8(t_05) <= resize(tmp_59(t_05), 67);
    adder_add_cast_9(t_05) <= resize(tmp_3(t_05), 67);
    adder_add_temp_4(t_05) <= adder_add_cast_8(t_05) + adder_add_cast_9(t_05);
    
    tmp_60(t_05) <= "011111111111111111111111111111111111111111111111111111111111111111" WHEN (adder_add_temp_4(t_05)(66) = '0') AND (adder_add_temp_4(t_05)(65) /= '0') ELSE
        "100000000000000000000000000000000000000000000000000000000000000000" WHEN (adder_add_temp_4(t_05)(66) = '1') AND (adder_add_temp_4(t_05)(65) /= '1') ELSE
        adder_add_temp_4(t_05)(65 DOWNTO 0);
  END GENERATE tmp_60_gen;


  rd_6_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        tmp_61 <= (OTHERS => to_signed(0, 66));
      ELSIF enb = '1' THEN
        tmp_61 <= tmp_60;
      END IF;
    END IF;
  END PROCESS rd_6_process;



  x_pred_gen: FOR ii15 IN 0 TO 1 GENERATE
    
    x_pred(ii15) <= X"7FFFFFFF" WHEN (tmp_61(ii15)(65) = '0') AND (tmp_61(ii15)(64 DOWNTO 47) /= "000000000000000000") ELSE
        X"80000000" WHEN (tmp_61(ii15)(65) = '1') AND (tmp_61(ii15)(64 DOWNTO 47) /= "111111111111111111") ELSE
        tmp_61(ii15)(47 DOWNTO 16) + ('0' & (tmp_61(ii15)(65) AND (tmp_61(ii15)(15) OR tmp_61(ii15)(14) OR tmp_61(ii15)(13) OR tmp_61(ii15)(12) OR tmp_61(ii15)(11) OR tmp_61(ii15)(10) OR tmp_61(ii15)(9) OR tmp_61(ii15)(8) OR tmp_61(ii15)(7) OR tmp_61(ii15)(6) OR tmp_61(ii15)(5) OR tmp_61(ii15)(4) OR tmp_61(ii15)(3) OR tmp_61(ii15)(2) OR tmp_61(ii15)(1) OR tmp_61(ii15)(0))));
  END GENERATE x_pred_gen;


  rd_61_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        x_pred_1 <= (OTHERS => to_signed(0, 32));
      ELSIF enb = '1' THEN
        x_pred_1 <= x_pred;
      END IF;
    END IF;
  END PROCESS rd_61_process;



  tmp_62_gen: FOR ii16 IN 0 TO 1 GENERATE
    tmp_62(ii16) <= resize(x_pred_1(ii16), 33);
  END GENERATE tmp_62_gen;


  rd_62_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        rd_62_reg <= (OTHERS => to_signed(0, 33));
      ELSIF enb = '1' THEN
        rd_62_reg(0 TO 1) <= tmp_62(0 TO 1);
        rd_62_reg(2 TO 43) <= rd_62_reg(0 TO 41);
      END IF;
    END IF;
  END PROCESS rd_62_process;

  tmp_63(0 TO 1) <= rd_62_reg(42 TO 43);


  tmp_64_gen: FOR t_06 IN 0 TO 1 GENERATE
    adder_add_cast_10(t_06) <= resize(tmp_63(t_06), 34);
    adder_add_cast_11(t_06) <= resize(tmp_56(t_06), 34);
    adder_add_temp_5(t_06) <= adder_add_cast_10(t_06) + adder_add_cast_11(t_06);
    
    tmp_64(t_06) <= "011111111111111111111111111111111" WHEN (adder_add_temp_5(t_06)(33) = '0') AND (adder_add_temp_5(t_06)(32) /= '0') ELSE
        "100000000000000000000000000000000" WHEN (adder_add_temp_5(t_06)(33) = '1') AND (adder_add_temp_5(t_06)(32) /= '1') ELSE
        adder_add_temp_5(t_06)(32 DOWNTO 0);
  END GENERATE tmp_64_gen;


  rd_68_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        tmp_65 <= (OTHERS => to_signed(0, 33));
      ELSIF enb = '1' THEN
        tmp_65 <= tmp_64;
      END IF;
    END IF;
  END PROCESS rd_68_process;



  tmp_57_gen: FOR ii17 IN 0 TO 1 GENERATE
    
    tmp_57(ii17) <= X"7FFFFFFF" WHEN (tmp_65(ii17)(32) = '0') AND (tmp_65(ii17)(31) /= '0') ELSE
        X"80000000" WHEN (tmp_65(ii17)(32) = '1') AND (tmp_65(ii17)(31) /= '1') ELSE
        tmp_65(ii17)(31 DOWNTO 0);
  END GENERATE tmp_57_gen;


  tmp_66 <= to_signed(16#00000000#, 32);

  w_est_1 <= tmp_57(to_integer(tmp_66));

  alpha_bypass_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        alpha_bypass_reg <= to_signed(0, 32);
      ELSIF enb_1_1000000_1 = '1' THEN
        alpha_bypass_reg <= w_est_1;
      END IF;
    END IF;
  END PROCESS alpha_bypass_process;

  
  w_est_tmp <= w_est_1 WHEN enb_1_1000000_1 = '1' ELSE
      alpha_bypass_reg;

  w_est <= std_logic_vector(w_est_tmp);

END rtl;

