-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\untitled_25_mayis\Kalman_28_yeni_tc.vhd
-- Created: 2026-05-28 21:02:51
-- 
-- Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Kalman_28_yeni_tc
-- Source Path: Kalman_28_yeni_tc
-- Hierarchy Level: 1
-- 
-- Master clock enable input: clk_enable
-- 
-- enb         : identical to clk_enable
-- enb_1_1_1   : identical to clk_enable
-- enb_1_1000000_0: 1000000x slower than clk with last phase
-- enb_1_1000000_1: 1000000x slower than clk with phase 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Kalman_28_yeni_tc IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        enb                               :   OUT   std_logic;
        enb_1_1_1                         :   OUT   std_logic;
        enb_1_1000000_0                   :   OUT   std_logic;
        enb_1_1000000_1                   :   OUT   std_logic
        );
END Kalman_28_yeni_tc;


ARCHITECTURE rtl OF Kalman_28_yeni_tc IS

  -- Signals
  SIGNAL count1000000                     : unsigned(19 DOWNTO 0);  -- ufix20
  SIGNAL comp_0_tmp                       : std_logic;
  SIGNAL phase_0_tmp                      : std_logic;
  SIGNAL phase_0                          : std_logic;
  SIGNAL enb_1_1000000_0_1                : std_logic;
  SIGNAL comp_1_tmp                       : std_logic;
  SIGNAL phase_1_tmp                      : std_logic;
  SIGNAL phase_1                          : std_logic;
  SIGNAL enb_1_1000000_1_1                : std_logic;

BEGIN
  enb <= clk_enable;

  enb_1_1_1 <= clk_enable;

  -- Count limited, Unsigned Counter
  --  initial value   = 1
  --  step value      = 1
  --  count to value  = 999999
  counter_1000000_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        count1000000 <= to_unsigned(16#00001#, 20);
      ELSIF clk_enable = '1' THEN
        IF count1000000 >= to_unsigned(16#F423F#, 20) THEN 
          count1000000 <= to_unsigned(16#00000#, 20);
        ELSE 
          count1000000 <= count1000000 + to_unsigned(16#00001#, 20);
        END IF;
      END IF;
    END IF;
  END PROCESS counter_1000000_process;


  
  comp_0_tmp <= '1' WHEN count1000000 = to_unsigned(16#F423F#, 20) ELSE
      '0';

  phase_0_tmp <= comp_0_tmp AND clk_enable;

  phase_delay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        phase_0 <= '0';
      ELSIF clk_enable = '1' THEN
        phase_0 <= phase_0_tmp;
      END IF;
    END IF;
  END PROCESS phase_delay_process;


  enb_1_1000000_0_1 <= phase_0 AND clk_enable;

  enb_1_1000000_0 <= enb_1_1000000_0_1;

  
  comp_1_tmp <= '1' WHEN count1000000 = to_unsigned(16#00000#, 20) ELSE
      '0';

  phase_1_tmp <= comp_1_tmp AND clk_enable;

  phase_delay_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        phase_1 <= '1';
      ELSIF clk_enable = '1' THEN
        phase_1 <= phase_1_tmp;
      END IF;
    END IF;
  END PROCESS phase_delay_1_process;


  enb_1_1000000_1_1 <= phase_1 AND clk_enable;

  enb_1_1000000_1 <= enb_1_1000000_1_1;

END rtl;

