-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\untitled_25_mayis\Kalman_28_yeni_pkg.vhd
-- Created: 2026-05-28 21:02:51
-- 
-- Generated by MATLAB 26.1, HDL Coder 26.1, and Simulink 26.1
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE Kalman_28_yeni_pkg IS
  TYPE vector_of_signed65 IS ARRAY (NATURAL RANGE <>) OF signed(64 DOWNTO 0);
  TYPE matrix_of_signed32 IS ARRAY (NATURAL RANGE <>, NATURAL RANGE <>) OF signed(31 DOWNTO 0);
  TYPE vector_of_signed32 IS ARRAY (NATURAL RANGE <>) OF signed(31 DOWNTO 0);
  TYPE vector_of_signed64 IS ARRAY (NATURAL RANGE <>) OF signed(63 DOWNTO 0);
  TYPE vector_of_signed66 IS ARRAY (NATURAL RANGE <>) OF signed(65 DOWNTO 0);
  TYPE matrix_of_signed98 IS ARRAY (NATURAL RANGE <>, NATURAL RANGE <>) OF signed(97 DOWNTO 0);
  TYPE matrix_of_signed65 IS ARRAY (NATURAL RANGE <>, NATURAL RANGE <>) OF signed(64 DOWNTO 0);
  TYPE vector_of_signed33 IS ARRAY (NATURAL RANGE <>) OF signed(32 DOWNTO 0);
  TYPE matrix_of_signed64 IS ARRAY (NATURAL RANGE <>, NATURAL RANGE <>) OF signed(63 DOWNTO 0);
  TYPE vector_of_signed99 IS ARRAY (NATURAL RANGE <>) OF signed(98 DOWNTO 0);
  TYPE vector_of_signed34 IS ARRAY (NATURAL RANGE <>) OF signed(33 DOWNTO 0);
  TYPE vector_of_signed98 IS ARRAY (NATURAL RANGE <>) OF signed(97 DOWNTO 0);
  TYPE vector_of_signed100 IS ARRAY (NATURAL RANGE <>) OF signed(99 DOWNTO 0);
  TYPE vector_of_signed67 IS ARRAY (NATURAL RANGE <>) OF signed(66 DOWNTO 0);
  TYPE matrix_of_signed33 IS ARRAY (NATURAL RANGE <>, NATURAL RANGE <>) OF signed(32 DOWNTO 0);
END Kalman_28_yeni_pkg;

